(()=>{'use strict';
const $=id=>document.getElementById(id), clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,Number(n)||0)), money=n=>'$'+Math.round(n).toLocaleString();
const KEY='lifeSim_v6_contextualWorld';
const personalities=['Kind','Ambitious','Curious','Calm','Bold','Funny','Romantic','Practical','Creative','Competitive','Shy','Social','Stubborn','Empathetic','Independent','Adventurous'];
const talents=['Music','Writing','Art','Sports','Math','Science','Programming','Business','Languages','Acting','Fashion','Cooking','Photography','Gaming','Leadership','Dance'];
const names=['Mina','Lena','Sofia','Emma','Ari','Nora','Maya','Iris','Lina','Elena','Avery','Jade','Theo','Noah','Leo','Eli','Kai','Lucas','Julian','Alex'];
const places=['Ho Chi Minh City, Vietnam','Seoul, South Korea','Tokyo, Japan','London, UK','Paris, France','New York City, USA','Vancouver, Canada','Singapore','Bangkok, Thailand','Sydney, Australia'];
const weatherTypes=['Sunny','Cloudy','Rainy','Stormy','Cool','Hot','Windy'];
const moods=['good','busy','quiet','excited','stressed','curious','tired','happy'];
let mode='custom',S=null,active='home',subtab='actions',selectedP=[],selectedT=[];
const rand=a=>a[Math.floor(Math.random()*a.length)], esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(t){const x=$('toast');x.textContent=t;x.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>x.classList.remove('show'),1800)}
function chips(id,list,sel){$(id).innerHTML=list.map(x=>`<button type="button" class="chip ${sel.includes(x)?'selected':''}" data-chip="${esc(x)}">${esc(x)}</button>`).join('')}
chips('personality',personalities,selectedP);chips('talents',talents,selectedT);
$('personality').onclick=e=>{const b=e.target.closest('[data-chip]');if(!b)return;const v=b.dataset.chip;if(selectedP.includes(v))selectedP=selectedP.filter(x=>x!==v);else if(selectedP.length<5)selectedP.push(v);chips('personality',personalities,selectedP)};
$('talents').onclick=e=>{const b=e.target.closest('[data-chip]');if(!b)return;const v=b.dataset.chip;if(selectedT.includes(v))selectedT=selectedT.filter(x=>x!==v);else if(selectedT.length<5)selectedT.push(v);chips('talents',talents,selectedT)};
document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('.mode').forEach(x=>x.classList.toggle('active',x===b));if(mode!=='custom')randomize(false)});
function randomize(all=true){$('c-name').value=rand(names);$('c-place').value=rand(places);$('c-gender').value=rand(['Girl','Boy','Non-binary','Other']);$('c-attraction').value=rand(['Men','Women','All genders','Not sure yet','Asexual / romantic']);$('c-wealth').value=rand(['Struggling','Modest','Middle class','Comfortable','Wealthy']);$('c-home').value=rand(['Warm and stable','Busy but loving','Strict','Chaotic','Quiet','Highly privileged','Unpredictable']);$('c-dob').value=`${1998+Math.floor(Math.random()*15)}-${String(1+Math.floor(Math.random()*12)).padStart(2,'0')}-${String(1+Math.floor(Math.random()*27)).padStart(2,'0')}`;selectedP=[rand(personalities),rand(personalities)];selectedT=[rand(talents),rand(talents)];chips('personality',personalities,selectedP);chips('talents',talents,selectedT);if(all)toast('Character randomized')}
document.querySelectorAll('[data-random]').forEach(b=>b.onclick=()=>randomize(true));$('random-all').onclick=()=>randomize(true);
function mentalityFor(personality){const map={Calm:'Steady',Bold:'Bold',Ambitious:'Driven',Curious:'Curious',Funny:'Playful',Romantic:'Romantic',Competitive:'Competitive',Shy:'Reserved',Social:'Social',Independent:'Independent',Empathetic:'Empathetic'};return map[(personality||[])[0]]||'Balanced'}
function makePeople(age){const base=age<6?['Mom','Dad','Grandmother']:age<13?['Mom','Dad','Mia • classmate','Noah • neighbor']:age<18?['Mom','Dad','Mia • best friend','Noah • classmate','Jade • club member','Leo • crush']:['Mom','Dad','Mia • old friend','Noah • colleague','Jade • friend','Leo • connection'];return base.map((name,i)=>({name,rel:clamp(72-i*8+Math.floor(Math.random()*12)),memory:'A small shared memory waiting to be discovered.',mood:rand(moods),lastSeen:1+Math.floor(Math.random()*8),secretChance:Math.random()}))}
function initialWeather(){return {type:rand(weatherTypes),temp:20+Math.floor(Math.random()*17),humidity:40+Math.floor(Math.random()*50),forecast:[]}}
function lifeStage(){return S.age<1?'Infant':S.age<3?'Toddler':S.age<6?'Early childhood':S.age<13?'Child':S.age<16?'Young teen':S.age<18?'Older teen':S.age<65?'Adult':'Older adult'}
function caregiverNames(){return S.people.filter(p=>['Mom','Dad','Grandmother','Grandfather','Older sibling','Aunt','Uncle'].some(x=>p.name.includes(x))).map(p=>p.name)}
function primaryCaregiver(){return rand(caregiverNames())||'a caregiver'}
function autonomy(){return S.age<1?5:S.age<3?18:S.age<6?32:S.age<10?48:S.age<13?62:S.age<16?76:S.age<18?88:100}
function needDefaults(){return {hunger:35,hygiene:75,toilet:70,fun:65,social:60,comfort:75,sleep:75}}
function skillDefaults(){return {selfFeeding:0,potty:0,bathing:0,dressing:0,cooking:0,money:0,safety:0}}
function familyRules(){const strict=/Strict/.test(S.home), warm=/Warm|loving/.test(S.home);return {strictness:strict?78:warm?35:50,respect:strict?42:warm?82:62,permission:strict?75:50}}
function canIndependent(skill,minAge=0){return S.age>=minAge && (S.development?.skills?.[skill]||0)>=60}
function improve(skill,n=8){S.development.skills[skill]=clamp(S.development.skills[skill]+n)}
function need(k,n){S.needs[k]=clamp(S.needs[k]+n)}
function wants(){const w=[];if(S.needs.fun<55)w.push('Play');if(S.needs.social<50)w.push(S.age<6?'Caregiver attention':'See someone');if(S.needs.hunger>65)w.push('Food');if(S.age<6&&Math.random()<.45)w.push(rand(['Story time','Play outside','Favorite toy','Cuddle','Playdate']));return w.slice(0,3)}
function makeState(){const personality=selectedP.length?[...selectedP]:[rand(personalities)], talentsNow=selectedT.length?[...selectedT]:[rand(talents)];return {version:6,name:$('c-name').value.trim()||rand(names),dob:$('c-dob').value||'2010-01-01',place:$('c-place').value.trim()||rand(places),zodiac:$('c-zodiac').value==='auto'?'Unknown':$('c-zodiac').value,gender:$('c-gender').value,attraction:$('c-attraction').value,wealth:$('c-wealth').value,home:$('c-home').value,personality,talents:talentsNow,age:0,day:1,money:['Struggling','Modest'].includes($('c-wealth').value)?80:300,health:100,happiness:70,energy:100,stress:10,luck:clamp(35+Math.random()*30),mentality:mentalityFor(personality),gpa:null,school:null,people:makePeople(0),log:[],events:[],exams:[],messages:[],flags:{},weather:initialWeather(),inventory:{umbrella:0,raincoat:0,sweater:0,firewood:0,sunglasses:0,waterBottle:0},stall:null,finance:{savings:0,debt:0,investments:0},career:{job:null,reputation:0,skills:0},healthState:{fitness:50,sleep:70,illness:null},social:{followers:0,reputation:50,posts:0},romance:{status:'Single',partner:null,history:[]},travel:{trips:0,lastTrip:null},family:{closeness:65,tension:10},development:{skills:skillDefaults(),kindergarten:{asked:false,enrolled:false,preference:null,decision:null},milestones:[]},needs:needDefaults(),wants:[],permissions:{stand:null,yardSale:null},familyEvents:[],phone:{owned:false,model:null,price:600},giftRequests:[],traditions:{christmas:Math.random()<.72,lunarNewYear:/Vietnam|Korea|Singapore|China|Taiwan/.test($('c-place').value)||Math.random()<.3},giftHistory:[],current:{title:'Welcome to the world.',text:'Your story is beginning. At first, most of life happens through caregivers. Independence will be learned, not assumed.'}}}
function log(title,text){S.log.unshift({day:S.day,age:S.age,title,text});if(S.log.length>350)S.log.pop()}
function save(){if(!S)return;localStorage.setItem(KEY,JSON.stringify(S));$('save-status').textContent='Saved '+new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}
function exportSave(){if(!S)return;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(S,null,2)],{type:'application/json'}));a.download=`life-${S.name.replace(/\s+/g,'-')}.json`;a.click();URL.revokeObjectURL(a.href)}
function importFile(){$('import-file').click()}
$('import-file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{S=JSON.parse(await f.text());migrate();enterGame();toast('Save imported')}catch{toast('Invalid save file')}};
function migrate(){S.version=6;S.luck=clamp(S.luck??50);S.mentality=S.mentality||'Balanced';S.weather=S.weather||initialWeather();S.inventory=Object.assign({umbrella:0,raincoat:0,sweater:0,firewood:0,sunglasses:0,waterBottle:0},S.inventory||{});S.messages=S.messages||[];S.exams=S.exams||[];S.events=S.events||[];S.log=S.log||[];S.stall=S.stall||null;S.people=S.people||makePeople(S.age||0);S.finance=Object.assign({savings:0,debt:0,investments:0},S.finance||{});S.career=Object.assign({job:null,reputation:0,skills:0},S.career||{});S.healthState=Object.assign({fitness:50,sleep:70,illness:null},S.healthState||{});S.social=Object.assign({followers:0,reputation:50,posts:0},S.social||{});S.romance=Object.assign({status:'Single',partner:null,history:[]},S.romance||{});S.travel=Object.assign({trips:0,lastTrip:null},S.travel||{});S.family=Object.assign({closeness:65,tension:10},S.family||{});S.development=S.development||{skills:skillDefaults(),kindergarten:{asked:false,enrolled:false,preference:null,decision:null},milestones:[]};S.development.skills=Object.assign(skillDefaults(),S.development.skills||{});S.development.kindergarten=Object.assign({asked:false,enrolled:false,preference:null,decision:null},S.development.kindergarten||{});S.needs=Object.assign(needDefaults(),S.needs||{});S.wants=S.wants||[];S.permissions=Object.assign({stand:null,yardSale:null},S.permissions||{});S.familyEvents=S.familyEvents||[];S.phone=Object.assign({owned:false,model:null,price:600},S.phone||{});S.giftRequests=S.giftRequests||[];S.traditions=Object.assign({christmas:true,lunarNewYear:false},S.traditions||{});S.giftHistory=S.giftHistory||[]}
function highSchoolAge(){return 15}
function canUseOwnPhone(){return S.age>=highSchoolAge()&&S.phone&&S.phone.owned}
function lifeNav(){const a=[['home','🏠','My Life']];if(S.age<6){a.push(['family','👨‍👩‍👧','Family'],['people','🧸','People & play'],['development','🌱','Growing Up'])}else{a.push(['people','👥','People']);if(S.school)a.push(['school','📚','Education']);a.push(['places','🌎','World'],['business','💰','My Money'])}if(S.age>=highSchoolAge())a.push(['phone','📱','Phone']);if(S.age>=13)a.push(['family','❤️','Relationships']);if(S.age>=16)a.push(['career','💼','Work & Money']);if(S.age>=18)a.push(['health','🩺','Health']);a.push(['world','📖','Life History']);return a}
function needUrgency(k,v){return k==='hunger'||k==='toilet'?v:100-v}
function needLabel(k,v){const u=needUrgency(k,v);return u>=80?'Urgent':u>=60?'Needs attention':u>=35?'Okay':'Comfortable'}
function requestGift(item,occasion){if(S.age<6){toast('You are too young to make this specific request.');return}const old=S.giftRequests.find(r=>r.item===item&&r.occasion===occasion&&!r.resolved);if(old){old.begging=(old.begging||1)+1;if(old.begging>2)S.family.tension=clamp(S.family.tension+2);log('Asked again',`You ask again for ${item} for ${occasion}. You still have to wait until that day.`);return}S.giftRequests.push({item,occasion,requestedDay:S.day,requestedAge:S.age,begging:1,resolved:false});log('Gift request',`You ask for ${item} for ${occasion}. Nothing is given now; the request stays pending until ${occasion}.`)}
function resolveGiftRequests(occasion){S.giftRequests.filter(r=>!r.resolved&&r.occasion===occasion).forEach(r=>{r.resolved=true;const wb={Struggling:-25,Modest:-12,'Middle class':0,Comfortable:12,Wealthy:24,'Extremely wealthy':35}[S.wealth]||0;const chance=clamp(38+wb+(S.family.closeness-50)/3-S.family.tension/5+(familyRules().respect-50)/4-(r.begging>3?(r.begging-3)*5:0));const got=Math.random()*100<chance;if(got&&/smartphone/.test(r.item)){S.phone.owned=true;S.phone.model='First smartphone';S.giftHistory.unshift({day:S.day,age:S.age,item:'Smartphone',occasion,reaction:null});log(`🎁 ${occasion} gift`,`You finally unwrap the $600 smartphone you asked for.`)}else if(got){S.giftHistory.unshift({day:S.day,age:S.age,item:r.item,occasion,reaction:null});log(`🎁 ${occasion} gift`,`You receive ${r.item}.`)}else log(`🎁 ${occasion}`,`You hoped for ${r.item}, but you do not receive it. Money, household rules, relationships and how often you begged all mattered.`)})}
function holidayTick(){const y=((S.day-1)%365)+1;if(y===1&&S.traditions.lunarNewYear&&S.age>=2){const amt=10+Math.floor(Math.random()*71);S.money+=amt;log('🧧 Lucky money',`Relatives give you ${money(amt)}. You can save it or use it toward something you want.`)}if(y===359&&S.traditions.christmas){resolveGiftRequests('Christmas');if(Math.random()<.75){const item=rand(['a book','new clothes','a board game','headphones','art supplies','sports gear','a bicycle','something handmade']);S.giftHistory.unshift({day:S.day,age:S.age,item,occasion:'Christmas',reaction:null});log('🎄 Christmas present',`You receive ${item}. What you feel privately and what you show can be different.`)}}}
function buyPhoneWithSavings(){if(S.age<highSchoolAge()){toast('You can save now, but independent phone use starts in high school.');return}const total=S.money+S.finance.savings;if(total<600){toast(`You need ${money(600-total)} more.`);return}let n=600,c=Math.min(S.money,n);S.money-=c;n-=c;if(n)S.finance.savings-=n;S.phone.owned=true;S.phone.model='First smartphone';log('📱 First phone','You spend $600 of your own money and savings on your first smartphone.')}
function schedule(age){if(age>=3&&age<=5&&S.development?.kindergarten?.enrolled){S.exams=[];S.school={name:rand(['Little Steps Kindergarten','Sunflower Early Learning','Neighborhood Kindergarten']),grade:'Kindergarten',className:rand(['Sun','Moon','Rainbow','Bears']),attendance:96,gpa:null,rank:null,subjects:[{name:'Language & stories',score:70,trend:'→'},{name:'Numbers & patterns',score:65,trend:'→'},{name:'Movement',score:75,trend:'↑'},{name:'Social skills',score:68,trend:'→'}],clubs:[],contests:[]};return}if(age>=6&&age<=18){S.exams=[];const subs=['Mathematics','English','Literature','Science','History','Computer Science'];subs.forEach((subject,i)=>S.exams.push({subject,days:4+i*5,score:null,type:i%3===0?'Midterm':i%3===1?'Quiz':'Final'}));S.school={name:rand(['Riverside Academy','Central International School','Westside High','Sunrise Secondary School']),grade:age<=11?'Primary':age<=14?'Middle school':'High school',className:`${age}-${String.fromCharCode(65+Math.floor(Math.random()*4))}`,attendance:96,gpa:S.gpa??(2.8+Math.random()*1.1),rank:Math.floor(8+Math.random()*25),subjects:subs.map((x,i)=>({name:x,score:72+Math.floor(Math.random()*24),trend:i%2?'→':'↑'})),clubs:[],contests:[]}}else S.school=null}
function setWeather(){const old=S.weather?.type;let type=rand(weatherTypes);if(old&&Math.random()<.35)type=old;const ranges={Sunny:[24,35],Cloudy:[20,31],Rainy:[19,29],Stormy:[18,28],Cool:[14,23],Hot:[30,39],Windy:[19,30]};const r=ranges[type];S.weather={type,temp:r[0]+Math.floor(Math.random()*(r[1]-r[0]+1)),humidity:40+Math.floor(Math.random()*55),forecast:Array.from({length:5},()=>{const t=rand(weatherTypes),rr=ranges[t];return {type:t,temp:rr[0]+Math.floor(Math.random()*(rr[1]-rr[0]+1))}})}}
function weatherAdvice(){const w=S.weather.type;if(['Rainy','Stormy'].includes(w))return 'Rain gear helps outdoors; staying in can be more comfortable.';if(w==='Hot')return 'Heat increases thirst and fatigue; water, shade and A/C matter.';if(w==='Cool')return 'A sweater or warmer room helps comfort.';if(w==='Sunny')return 'Sunglasses, water and sunscreen are useful outside.';return 'The weather is mild enough for most plans.'}
function ensureEvents(){S.events=[];if(S.age>=6&&S.age<=18)S.events.push({kind:'school',title:'School day',text:'Classes, teachers, classmates and unscheduled moments are waiting.'});if(S.age>=13)S.events.push({kind:'social',title:'Your social world is changing',text:'People remember what happens between you, not just a relationship score.'});S.events.push({kind:'world',title:'Life keeps moving',text:'Someone nearby is making a decision that may or may not cross your path.'})}
function developmentalEvents(){
 if(S.age===3&&!S.development.kindergarten.asked){S.development.kindergarten.asked=true;S.events.unshift({kind:'popup',title:'Kindergarten?',text:`Your caregivers are discussing kindergarten. Their strictness is ${familyRules().strictness}% and respect for your preference is ${familyRules().respect}%.`,special:'kindergarten'});S.current={title:'A family decision',text:'Kindergarten has become a real question in your household.'}}
 if(S.age<=6&&Math.random()<.12){const ev=rand(['A relative is planning a baby shower.','A child nearby is having a birthday party.','A caregiver suggests arranging a playdate.','Grandparents want to visit this weekend.']);S.familyEvents.unshift({day:S.day,text:ev});log('Family & childhood event',ev)}
}
function advance(days){for(let d=0;d<days;d++){S.day++;S.energy=clamp(S.energy-2);need('hunger',2);need('toilet',2);need('hygiene',-1);need('sleep',-1);need('fun',-1);need('social',-1);S.stress=clamp(S.stress+(Math.random()<.15?2:-1));S.happiness=clamp(S.happiness+(Math.random()-.48)*2);S.exams.forEach(x=>x.days--);holidayTick();if(S.day%7===0){setWeather();worldTick();developmentalEvents();}if(S.stall?.active)stallTick()}if(days>0&&Math.random()<.65)randomLifeEvent()}
function worldTick(){S.people.forEach(p=>{p.rel=clamp(p.rel+(Math.random()<.52?1:-1));p.mood=rand(moods);p.lastSeen++;if(Math.random()<.08){p.memory='Something changed in their life while you were elsewhere.';log('Someone else’s life',`${p.name} had a change you were not directly involved in.`)}});if(S.school)S.school.subjects.forEach(s=>{s.score=clamp(s.score+(Math.random()<.45?1:-1),0,100)});if(Math.random()<.2)S.luck=clamp(S.luck+(Math.random()<.5?-1:1))}
function randomLifeEvent(){const pool=[];if(S.age<6)pool.push(['Family moment','A family member does something ordinary that becomes part of your early memories.']);if(S.age>=6&&S.age<=18)pool.push(['Unexpected school moment','A teacher changes the plan for the day. A classmate reacts strongly.'],['New school opportunity','Someone mentions a club, contest or activity you could join.']);if(S.age>=13)pool.push(['New message','Someone you know sends a message you did not expect.'],['Social ripple','You hear two different versions of the same story about someone you know.']);pool.push(['Neighborhood life','A nearby family is celebrating, moving, arguing, renovating or simply changing their routine.'],['Small coincidence','A normal trip puts you in the same place as someone from another part of your life.']);if(S.weather.type==='Rainy')pool.push(['Rainy-day coincidence','The rain changes everyone’s plans. Someone you know ends up somewhere unexpected.']);const e=rand(pool);S.current={title:e[0],text:e[1]};log(e[0],e[1]);S.events.unshift({kind:'popup',title:e[0],text:e[1],day:S.day,choices:['Look into it','Let it pass']});if(S.events.length>12)S.events.pop()}
function luckyRoll(base=0){return clamp(base+(Math.random()*100<S.luck?10:0)+(Math.random()*100<S.luck?5:0),0,100)}
function act(id,arg){if(!S)return;
if(id==='feed'){const c=primaryCaregiver();need('hunger',-55);S.energy=clamp(S.energy+12);if(S.age>=1){improve('selfFeeding',10);log('Learning to eat',`${c} helps you eat and lets you practice doing part of it yourself. Self-feeding is ${S.development.skills.selfFeeding}%.`)}else log('Being fed',`${c} feeds you because you cannot feed yourself yet.`)}
else if(id==='eatSelf'){if(!canIndependent('selfFeeding',1)){toast('You are still learning to eat independently.');return}need('hunger',-55);S.energy=clamp(S.energy+12);log('Eating independently','You manage your own meal with age-appropriate supervision nearby.')}
else if(id==='pottyHelp'){const c=primaryCaregiver();need('toilet',-65);improve('potty',12);log('Potty training',`${c} helps you notice the signal, get there in time, and practice. Potty skill: ${S.development.skills.potty}%.`)}
else if(id==='toiletSelf'){if(!canIndependent('potty',2)){toast('You still need help with toileting.');return}need('toilet',-65);log('Bathroom','You use the bathroom by yourself.')}
else if(id==='batheHelp'){const c=primaryCaregiver();need('hygiene',25);improve('bathing',8);log('Bath time',`${c} helps wash you safely while you learn the routine. Bathing skill: ${S.development.skills.bathing}%.`)}
else if(id==='batheSelf'){if(!canIndependent('bathing',6)){toast('You still need supervision or help bathing.');return}need('hygiene',25);log('Shower','You take care of your own shower routine.')}
else if(id==='dressHelp'){const c=primaryCaregiver();improve('dressing',10);log('Getting dressed',`${c} helps choose and put on your clothes. You practice parts you can manage. Dressing skill: ${S.development.skills.dressing}%.`)}
else if(id==='dressSelf'){if(!canIndependent('dressing',4)){toast('You are still learning to dress independently.');return}log('Dressed yourself','You choose and put on your own clothes.')}
else if(id==='cook'){if(S.age<8){toast('Cooking requires caregiver help at this age.');return}improve('cooking',S.age<13?6:10);need('hunger',-40);log('Cooking',S.age<13?'You cook a simple item with supervision.':'You prepare food with growing independence.')}
else if(id==='play'){need('fun',30);need('social',5);S.happiness=clamp(S.happiness+5);log('Play',S.age<6?'Play is serious learning right now: movement, imagination, language and social practice.':'You make time for something fun.')}
else if(id==='playdate'){if(S.age>10){toast('At your age, hanging out replaces formal playdates.');return}need('social',30);need('fun',20);const p=rand(S.people.filter(x=>!/Mom|Dad|Grand/.test(x.name)))||{name:'another child'};log('Playdate',`Your caregivers coordinate a playdate with ${p.name}. Adults handle the logistics while you handle the friendship.`)}
else if(id==='kindergartenYes'||id==='kindergartenNo'){S.development.kindergarten.preference=id==='kindergartenYes';const r=familyRules(), childYes=id==='kindergartenYes';const parentNeed=(S.wealth==='Struggling'||S.home==='Busy but loving')?20:0;const score=(childYes?r.respect:-r.respect/2)+parentNeed+(50-r.strictness)/2;const enrolled=score>25||(!childYes&&r.strictness>75);S.development.kindergarten.enrolled=enrolled;S.development.kindergarten.decision=enrolled?'Enrolled':'Staying home / alternative care';log('Kindergarten decision',enrolled?'Your caregivers decide you will attend kindergarten. Your preference was part of the discussion, but family circumstances mattered too.':'Your family chooses home/relative care or another early-childhood arrangement for now.');S.events=S.events.filter(e=>e.special!=='kindergarten');schedule(S.age)}
else if(id==='askStand'){requestPermission('stand')}
else if(id==='askYard'){requestPermission('yardSale')}
else if(id==='study'){if(!S.school){toast('There is no current school schedule.');return}const sub=S.school.subjects.find(s=>s.name===arg)||rand(S.school.subjects);S.energy=clamp(S.energy-12);S.stress=clamp(S.stress+3);sub.score=clamp(sub.score+2+Math.floor(Math.random()*3));log('Study session',`You focused on ${sub.name}. Your current score moved to ${sub.score}.`)}
else if(id==='exam'){const x=S.exams.find(e=>e.subject===arg);if(!x)return;if(x.days>0){toast(`The ${x.subject} exam is in ${x.days} days.`);return}const sub=S.school.subjects.find(s=>s.name===x.subject);x.score=clamp(Math.round(sub.score+(Math.random()-.25)*18+(S.luck-50)/5),0,100);log(`${x.subject} exam`,x.score>=70?`You finished with ${x.score}%.`:`The exam was difficult. You scored ${x.score}%.`);S.stress=clamp(S.stress+8);S.happiness=clamp(S.happiness+(x.score>=70?4:-3))}
else if(id==='school'){S.school?.attendance&&(S.school.attendance=clamp(S.school.attendance+.1));S.energy=clamp(S.energy-8);log('School','You attend classes. Something useful, awkward, funny or strange may happen between lessons.');if(Math.random()<.3)randomLifeEvent()}
else if(id==='friend'){const chosen=Number.isInteger(Number(arg))?S.people[Number(arg)]:null;const pool=S.people.filter(x=>!['Mom','Dad','Grandmother'].includes(x.name));const p=chosen||rand(pool.length?pool:S.people);p.rel=clamp(p.rel+6);p.memory='You spent time together today.';p.lastSeen=0;S.happiness=clamp(S.happiness+5);log('Time with '+p.name,`You made a new memory together. ${p.name} seems ${p.mood}.`)}
else if(id==='messagePerson'){const p=S.people[Number(arg)]||rand(S.people);S.messages.unshift({from:p.name,text:'You reached out first. They replied and the conversation is now open.',day:S.day,read:true});p.rel=clamp(p.rel+2);log('Message to '+p.name,'You started a conversation.');}
else if(id==='message'){if(!canUseOwnPhone()){toast(S.age<highSchoolAge()?'Personal phone use starts in high school.':'You need your own phone first.');return}const p=rand(S.people);S.messages.unshift({from:p.name,text:rand(['Are you around later?','I need to tell you something.','Did you hear what happened?','Want to do something this weekend?']),day:S.day,read:false});log('New message',`${p.name} sent you a message.`)}
else if(id==='reply'){if(!canUseOwnPhone()){toast('You need your own phone first.');return}const m=S.messages.find(x=>!x.read)||S.messages[0];if(m){m.read=true;const p=S.people.find(x=>x.name===m.from);if(p)p.rel=clamp(p.rel+4);log('Conversation',`You replied to ${m.from}. The conversation continues outside your control.`)}}
else if(id==='walk'){S.energy=clamp(S.energy-6);S.happiness=clamp(S.happiness+5);if(['Rainy','Stormy'].includes(S.weather.type)&&!S.inventory.umbrella&&!S.inventory.raincoat){S.health=clamp(S.health-3);log('Caught in the rain','You went outside without rain protection and came back soaked.')}else log('Out and about',`You went outside in ${S.weather.type.toLowerCase()} weather. ${weatherAdvice()}`)}
else if(id==='exercise'){S.energy=clamp(S.energy-14);S.health=clamp(S.health+3);S.stress=clamp(S.stress-4);log('Exercise','You worked out. Your body feels different for the rest of the day.')}
else if(id==='sleep'){S.energy=clamp(S.energy+55);S.stress=clamp(S.stress-12);advance(1);log('Sleep','You slept and woke up to a new day.')}
else if(id==='meal'){if(S.age<1)act('feed');else if(canIndependent('selfFeeding',1))act('eatSelf');else act('feed');return}
else if(id==='family'){const p=rand(S.people.filter(x=>['Mom','Dad','Grandmother'].includes(x.name))||S.people);p.rel=clamp(p.rel+4);p.memory='You had a family moment today.';log('Family time',`You spent time with ${p.name}.`)}
else if(id==='shower'){act(canIndependent('bathing',6)?'batheSelf':'batheHelp');return}
else if(id==='dress'){act(canIndependent('dressing',4)?'dressSelf':'dressHelp');return}
else if(id==='useGear'){const item=arg;if(S.inventory[item]>0){S.inventory[item]--;log('Used '+gearName(item),gearUse(item))}else toast('You do not own that item.')}
else if(id==='homeComfort'){const item=arg;log('Home comfort',gearUse(item));if(item==='ac')S.energy=clamp(S.energy+3);if(item==='fan')S.stress=clamp(S.stress-3);if(item==='fireplace')S.happiness=clamp(S.happiness+4)}
else if(id==='travel'){S.money=Math.max(0,S.money-20);S.energy=clamp(S.energy-15);log('Travel','You went somewhere new. A trip can create opportunities, expenses or people you never expected.')}
else if(id==='work'){if(S.age<16){toast('Local rules usually limit regular paid work before the mid-teens.');return}const pay=20+Math.floor(S.luck/5)+Math.floor(Math.random()*25);S.money+=pay;S.energy=clamp(S.energy-20);log('Work shift',`You earned ${money(pay)}. The job also introduced you to another slice of everyday life.`)}
else if(id==='business'){if(S.age<6){toast('Selling is a caregiver-led activity at this age.');return}if(S.age<16&&S.permissions.stand!==true){requestPermission('stand');return}active='business';log('Business idea','You started thinking like a seller: what to offer, who needs it, and what they will actually pay.');}
else if(id==='startStall'){startStall()}
else if(id==='stallSale'){runStall()}
else if(id==='club'){if(S.school){const c=rand(['Art Club','Debate','Science Club','Football','Drama','Coding','Music','Photography']);if(!S.school.clubs.includes(c))S.school.clubs.push(c);log('Club','You explored '+c+'. New people and opportunities can grow from this.')}}
else if(id==='contest'){if(S.school){const c=rand(['Math Olympiad','Science Fair','Debate Tournament','Art Showcase','Coding Challenge','School Sports Meet']);S.school.contests.push({name:c,status:'Considering'});log('Contest opportunity',`A ${c} opportunity appeared. You can decide whether it is worth your time.`)}}
else if(id==='social'){if(!canUseOwnPhone()){toast('You need your own phone first.');return}S.social.posts++;const gain=Math.max(0,Math.floor(Math.random()*8+(S.luck-50)/15));S.social.followers+=gain;log('Social feed',`You posted or interacted online. ${gain?gain+' new people followed you.':'It was a quiet post.'}`);if(Math.random()<.35)act('message')}
else if(id==='healthCheck'){S.money=Math.max(0,S.money-15);S.health=clamp(S.health+5);S.healthState.illness=null;log('Health check','You checked in on your health and addressed small problems before they grew.')}
else if(id==='therapy'){S.money=Math.max(0,S.money-20);S.stress=clamp(S.stress-18);S.happiness=clamp(S.happiness+5);log('Mental wellbeing','You spent time working through stress and perspective.')}
else if(id==='careerSkill'){S.career.skills++;S.energy=clamp(S.energy-10);log('Skill building',`You practiced a career skill. Skill level is now ${S.career.skills}.`)}
else if(id==='applyJob'){if(S.age<16){toast('Regular paid jobs unlock later in the teen years.');return}S.career.job=rand(['Cafe assistant','Retail associate','Tutor','Junior creator','Office assistant']);log('New job',`You were offered work as a ${S.career.job}.`)}
else if(id==='saveMoney'){const amount=Math.min(S.money,25);S.money-=amount;S.finance.savings+=amount;log('Savings',`You moved ${money(amount)} into savings.`)}
else if(id==='invest'){if(S.age<18){toast('Investing is available in adulthood in this simulation.');return}const amount=Math.min(S.money,50);S.money-=amount;S.finance.investments+=amount;log('Investment',`You invested ${money(amount)}. Its future value is uncertain.`)}
else if(id==='familyTalk'){S.family.closeness=clamp(S.family.closeness+4);S.family.tension=clamp(S.family.tension-2);log('Family conversation','You had a real conversation at home. It may shape how family members respond later.')}
else if(id==='romance'){if(S.age<13){toast('Romantic storylines become available in the teen years.');return}const candidates=S.people.filter(p=>!['Mom','Dad','Grandmother'].includes(p.name));const p=rand(candidates);if(!p)return;S.romance.history.push({day:S.day,age:S.age,name:p.name,event:'A spark or possibility appeared.'});p.rel=clamp(p.rel+3);log('A possibility',`A moment with ${p.name} felt different. Nothing is guaranteed from here.`)}
else if(id==='tripPlan'){const cost=40+Math.floor(Math.random()*80);if(S.money<cost){toast('This trip costs more than you have available.');return}S.money-=cost;S.travel.trips++;S.travel.lastTrip='Day '+S.day;advance(2);log('Trip',`You spent ${money(cost)} on transport and a short trip. New surroundings created new possibilities.`)}
else if(id==='negotiate'){if(!S.stall?.active){toast('Open a stand or yard sale first.');return}const item=S.stall.items[0],offer=Math.max(1,Math.round(item.price*(.55+Math.random()*.35)));const accepted=Math.random()*100 < 45+(S.luck-50)/4;if(accepted&&item.stock>0){item.stock--;S.money+=offer;S.stall.revenue+=offer;log('Negotiation',`A buyer offered ${money(offer)} for ${item.name}. You negotiated and closed the sale.`)}else log('Negotiation',`A buyer offered ${money(offer)} for ${item.name}, but the deal fell through. Walking away can be part of selling.`)}
else if(id==='requestPhoneBirthday'){requestGift('a $600 smartphone','Birthday')}else if(id==='requestPhoneChristmas'){if(!S.traditions.christmas){toast('Christmas is not a gift occasion in this household.');return}requestGift('a $600 smartphone','Christmas')}else if(id==='buyPhone'){buyPhoneWithSavings()}else if(id==='giftGrateful'){const g=S.giftHistory.find(x=>!x.reaction);if(g){g.reaction='Expressed gratitude';S.family.closeness=clamp(S.family.closeness+2);log('Gift reaction',`You express gratitude for ${g.item}, regardless of any private mixed feelings.`)}}else if(id==='giftHide'){const g=S.giftHistory.find(x=>!x.reaction);if(g){g.reaction='Hid disappointment';log('Gift reaction',`You hide your disappointment about ${g.item}. Your private feeling and outward behavior are remembered separately.`)}}else if(id==='giftComplain'){const g=S.giftHistory.find(x=>!x.reaction);if(g){g.reaction='Complained';S.family.tension=clamp(S.family.tension+5);log('Gift reaction',`You complain about ${g.item}. Your family remembers how you reacted.`)}}else if(id==='eventChoice'){log('Event choice',arg==='Look into it'?'You decided the unexpected thing was worth your attention.':'You let it pass and continued with your own day.');S.events=S.events.filter(e=>e.kind!=='popup')}
render();save()}
function requestPermission(kind){const r=familyRules(), label=kind==='stand'?'lemonade/baking stand':'yard sale';const chance=clamp(72-r.strictness/3+r.respect/4+(S.family.closeness-50)/4);const ok=Math.random()*100<chance;S.permissions[kind]=ok;log('Asked for permission',ok?`Your caregivers approve the ${label}, with supervision and household rules.`:`Your caregivers say no to the ${label} for now. Their decision reflects safety, time, money and household rules.`);toast(ok?'Permission granted':'Permission denied for now')}
function gearCost(i){return {umbrella:12,raincoat:28,sweater:24,firewood:10,sunglasses:18,waterBottle:15}[i]||10}
function gearName(i){return {umbrella:'Umbrella',raincoat:'Raincoat',sweater:'Sweater',firewood:'Firewood',sunglasses:'Sunglasses',waterBottle:'Water bottle'}[i]||i}
function gearUse(i){return {umbrella:'You stayed drier under your umbrella.',raincoat:'Your raincoat kept the rain from ruining your plans.',sweater:'The sweater kept you warmer.',fireplace:'The fireplace made home warmer and calmer.',ac:'You cooled the room with A/C.',fan:'You cooled down with a fan.',sunglasses:'Your sunglasses made the bright weather easier on your eyes.',waterBottle:'You drank water and felt better prepared for the heat.'}[i]||'You used it.'}
function startStall(){if(S.stall?.active){toast('Your stall is already open.');return}S.stall={active:true,type:'Lemonade',items:[{name:'Lemonade',cost:2,price:5,stock:8,quality:70}],revenue:0,visitors:0,day:S.day,exaggeration:30};log('Small business','You set up a small selling stand. What you choose to sell, price, presentation and negotiation can change the outcome.')}
function runStall(){if(!S.stall?.active){startStall();return}let st=S.stall;let item=st.items[0];if(item.stock<=0){toast('You are sold out.');st.active=false;return}let buyers=1+Math.floor(Math.random()*4),sold=0,revenue=0;for(let i=0;i<buyers&&item.stock>0;i++){const demand=clamp(65+(item.quality-50)/2-(item.price-4)*10+(st.exaggeration-30)/4+(S.luck-50)/3,5,95);if(Math.random()*100<demand){item.stock--;sold++;revenue+=item.price}}st.revenue+=revenue;st.visitors+=buyers;S.money+=revenue;log('Stand sales',`You had ${buyers} visitors, sold ${sold} ${item.name}, and earned ${money(revenue)}. Some buyers negotiated; others simply walked away.`);if(item.stock===0)st.active=false}
function stallTick(){if(Math.random()<.55)runStall()}
function setStallItem(){const name=$('stall-item')?.value.trim()||'Homemade item',price=Math.max(1,Number($('stall-price')?.value)||5),stock=Math.max(1,Math.floor(Number($('stall-stock')?.value)||5)),quality=clamp(Number($('stall-quality')?.value)||70),ex=clamp(Number($('stall-exaggeration')?.value)||30);S.stall=S.stall||{active:true,revenue:0,visitors:0,day:S.day};S.stall.active=true;S.stall.items=[{name,cost:Math.max(0.2,price*.35),price,stock,quality}];S.stall.exaggeration=ex;log('Stand prepared',`You chose to sell ${name} at ${money(price)} each, with ${stock} available and a ${ex}% exaggeration level in your pitch.`);render();save()}
function today(){const arr=[];if(S.weather)arr.push(`<div class="row"><span>Weather</span><b>${esc(S.weather.type)} ${S.weather.temp}°C</b></div>`);const next=S.exams.filter(x=>x.score==null).sort((a,b)=>a.days-b.days)[0];if(next)arr.push(`<div class="row"><span>${esc(next.subject)}</span><b>${next.days<=0?'TODAY':next.days+' days'}</b></div>`);const unread=S.messages.filter(x=>!x.read).length;if(unread)arr.push(`<div class="row"><span>Unread messages</span><b>${unread}</b></div>`);if(S.stall?.active)arr.push(`<div class="row"><span>Open stand</span><b>${S.stall.items?.[0]?.stock||0} left</b></div>`);$('today-list').innerHTML=arr.join('')||'<p class="muted-text">Nothing urgent.</p>'}
function schoolPanel(){if(!S.school)return `<div class="dashboard"><div class="card wide"><h3>No school right now</h3><p class="muted-text">School becomes a living system during school-age years.</p></div></div>`;return `<div class="dashboard"><div class="card"><h3>${esc(S.school.name)}</h3><p>${S.school.grade} • Class ${S.school.className}</p>${S.school.gpa!=null?`<div class="row"><span>GPA</span><b>${S.school.gpa.toFixed(2)}</b></div><div class="row"><span>Class rank</span><b>#${S.school.rank}</b></div>`:`<div class="row"><span>Learning style</span><b>Play-based</b></div>`}<div class="row"><span>Attendance</span><b>${S.school.attendance.toFixed(1)}%</b></div></div><div class="card"><h3>Clubs & contests</h3><p class="muted-text">${S.school.clubs.length?S.school.clubs.join(' • '):'No club commitments yet.'}</p><div class="action-grid"><button class="action" data-act="club"><strong>Explore clubs</strong><small>Meet people and discover interests</small></button><button class="action" data-act="contest"><strong>Find contests</strong><small>Auditions, teams and competitions</small></button></div>${S.school.contests.map(c=>`<div class="row"><span>${esc(c.name)}</span><span class="tag">${esc(c.status)}</span></div>`).join('')}</div><div class="card wide"><h3>Subjects & academic scores</h3><div class="list">${S.school.subjects.map(s=>`<div class="row"><span style="min-width:60%"><b>${esc(s.name)}</b> <span class="tag">${s.trend}</span><div class="progress"><i style="width:${s.score}%"></i></div><button class="small" data-act="study" data-subject="${esc(s.name)}">Study this subject</button></span><b>${s.score}</b></div>`).join('')}</div></div><div class="card wide"><h3>Exam countdown & reminders</h3><div class="list">${S.exams.map(x=>`<div class="row"><span><b>${esc(x.subject)}</b><br><span class="muted-text">${x.type}</span></span><span class="countdown">${x.score!=null?'Score '+x.score:(x.days<=0?'TODAY':x.days+' days')}</span>${x.score==null&&x.days<=0?`<button class="small" data-exam="${esc(x.subject)}">Take exam</button>`:''}</div>`).join('')}</div></div></div>`}
function peoplePanel(){return `<div class="dashboard"><div class="card wide"><h3>People have lives outside you</h3><p class="muted-text">NPCs change while you are elsewhere. Their routines, moods, relationships and memories can create future encounters.</p></div>${S.people.map((p,i)=>`<div class="card"><h3>${esc(p.name)}</h3><p><span class="tag">${esc(p.mood)}</span> Relationship ${p.rel}</p><div class="progress"><i style="width:${p.rel}%"></i></div><p class="muted-text">Memory: ${esc(p.memory)}</p><p class="muted-text">Last seen ${p.lastSeen} day${p.lastSeen===1?'':'s'} ago.</p><div class="action-grid"><button class="action" data-person="${i}"><strong>Spend time</strong><small>Create a specific memory</small></button><button class="action" data-person-msg="${i}"><strong>Message</strong><small>Start a conversation</small></button></div></div>`).join('')}</div>`}
function phonePanel(){if(S.age<highSchoolAge())return `<div class="dashboard"><div class="card wide"><h3>📱 No independent phone yet</h3><p class="muted-text">Before high school, device access is contextual: a caregiver's phone, a shared tablet, school computer or a friend's device.</p></div></div>`;if(!S.phone.owned){const p=S.giftRequests.filter(r=>!r.resolved&&/smartphone/.test(r.item));return `<div class="dashboard"><div class="card wide"><h3>📱 Your first phone</h3><p>A smartphone costs <b>$600</b>. Cash: <b>${money(S.money)}</b> • Savings: <b>${money(S.finance.savings)}</b></p>${p.length?`<div class="stage-note">${p.map(r=>`Waiting for <b>${esc(r.occasion)}</b> • asked ${r.begging} time${r.begging===1?'':'s'}`).join('<br>')}</div>`:''}<div class="action-grid"><button class="action" data-act="buyPhone"><strong>Buy with my money</strong><small>Requires $600 cash + savings.</small></button><button class="action" data-act="requestPhoneBirthday"><strong>Ask for birthday</strong><small>Wait until the actual birthday.</small></button>${S.traditions.christmas?`<button class="action" data-act="requestPhoneChristmas"><strong>Ask for Christmas</strong><small>Wait until Christmas day.</small></button>`:''}</div></div></div>`}return `<div class="dashboard"><div class="card wide"><h3>📱 ${esc(S.phone.model||'My phone')}</h3><div class="row"><span>Messages</span><b>${S.messages.filter(x=>!x.read).length} unread</b></div><div class="row"><span>Followers</span><b>${S.social.followers}</b></div><div class="action-grid"><button class="action" data-act="message"><strong>Messages</strong><small>See who reaches out.</small></button><button class="action" data-act="social"><strong>Social feed</strong><small>Post or interact online.</small></button></div></div></div>`}
function placesPanel(){const young=S.age<6;return `<div class="dashboard"><div class="card wide"><h3>${young?'Care routines':'Daily life'} • ${lifeStage()}</h3><p class="muted-text">Actions change with age, learned skills, caregiver availability and household rules.</p><div class="action-grid">${young?quickActions().map(x=>`<button class="action" data-act="${x[0]}"><strong>${x[1]}</strong><small>${x[2]}</small></button>`).join(''):`<button class="action" data-act="meal"><strong>🍲 Eat</strong><small>Food and routine</small></button><button class="action" data-act="shower"><strong>🚿 Hygiene</strong><small>${canIndependent('bathing',6)?'Shower independently':'Get appropriate help'}</small></button><button class="action" data-act="dress"><strong>👗 Dress & style</strong><small>${canIndependent('dressing',4)?'Choose and dress yourself':'Family assistance'}</small></button><button class="action" data-act="cook"><strong>🍳 Cook</strong><small>${S.age<13?'Supervised simple cooking':'Growing independence'}</small></button>`}</div></div><div class="card"><h3>Outside & social</h3><div class="action-grid"><button class="action" data-act="walk"><strong>🚶 Go outside</strong><small>${young?'With an appropriate caregiver':'Parks, streets and chance encounters'}</small></button>${S.age<=10?`<button class="action" data-act="playdate"><strong>🧸 Playdate</strong><small>Adult-coordinated social time</small></button>`:''}${S.age>=13?`<button class="action" data-act="travel"><strong>✈️ Travel</strong><small>Permission/independence depends on age</small></button>`:''}</div></div></div>`}
function homePanel(){const urgent=S.events.filter(e=>e.kind==='popup').slice(0,3),gift=S.giftHistory.find(x=>!x.reaction);return `<div class="dashboard"><div class="card wide"><h3>What's happening?</h3>${urgent.map(e=>`<div class="event-card card"><b>${esc(e.title)}</b><p class="muted-text">${esc(e.text)}</p><div class="event-actions"><button data-event-choice="Look into it">Look into it</button><button data-event-choice="Let it pass">Let it pass</button></div></div>`).join('')||'<p class="muted-text">No urgent interruption right now. Ordinary life is still moving.</p>'}</div><div class="card"><h3>Right now</h3><div class="row"><span>${weatherIcon(S.weather.type)} Weather</span><b>${S.weather.type} • ${S.weather.temp}°C</b></div><p class="muted-text">${esc(weatherAdvice())}</p><div class="row"><span>Luck</span><b>${Math.round(S.luck)}%</b></div><div class="row"><span>Mentality</span><b>${esc(S.mentality)}</b></div></div><div class="card"><h3>What can I do?</h3><div class="action-grid">${quickActions().map(x=>`<button class="action" data-act="${x[0]}"><strong>${x[1]}</strong><small>${x[2]}</small></button>`).join('')}</div></div>${gift?`<div class="card wide"><h3>🎁 How do you react?</h3><p>You received <b>${esc(gift.item)}</b> for ${esc(gift.occasion)}. Your private feeling and outward response do not have to match.</p><div class="event-actions"><button data-act="giftGrateful">Express gratitude</button><button data-act="giftHide">Hide disappointment</button><button data-act="giftComplain">Complain</button></div></div>`:''}</div>`}
function quickActions(){const a=[];if(S.age<1){a.push(['feed','🍼 Be fed','A caregiver handles feeding'],['batheHelp','🛁 Bath time','Caregiver-led hygiene'],['play','🧸 Play','Sensory and social development']);return a}if(S.age<3){a.push(['meal','🍌 Eat / practice self-feeding','Caregiver help changes as skill grows'],['pottyHelp','🚽 Potty practice','Learn body signals with a caregiver'],['batheHelp','🛁 Bath with help','Safety first'],['dressHelp','👕 Get dressed','Caregiver helps while you learn'],['play','🧸 Play','Development happens through play']);return a}if(S.age<6){a.push(['meal','🍲 Eat','Independence depends on learned skill'],['play','🧩 Play','Imagination, movement and friends'],['playdate','👧 Playdate','Caregivers arrange the logistics'],['dress','👕 Get dressed','Help or independence depends on skill']);return a}if(S.age>=6&&S.age<=18)a.push(['school','🎓 Go to school','Attend classes and see what happens']);a.push(['meal','🍲 Eat','Take care of your body'],['friend','👥 See someone','Relationships have histories'],['walk','🚶 Go outside',weatherAdvice()]);if(S.age>=8)a.push(['cook','🍳 Cook','Complexity and supervision depend on age']);if(canUseOwnPhone())a.push(['message','📱 Check messages','Use your own phone']);return a}

function familyPanel(){return `<div class="dashboard"><div class="card"><h3>Family dynamics</h3><div class="row"><span>Closeness</span><b>${S.family.closeness}%</b></div><div class="row"><span>Tension</span><b>${S.family.tension}%</b></div><button class="action" data-act="familyTalk"><strong>Have a real conversation</strong><small>Build trust, resolve tension or uncover a concern.</small></button></div><div class="card"><h3>Romance & relationships</h3><p><b>${esc(S.romance.status)}</b>${S.romance.partner?' • '+esc(S.romance.partner):''}</p><p class="muted-text">Romance emerges from people, timing and history rather than an automatic match.</p><button class="action" data-act="romance"><strong>Be open to connection</strong><small>See whether an existing relationship changes.</small></button></div></div>`}
function healthPanel(){return `<div class="dashboard"><div class="card"><h3>Health</h3><div class="row"><span>Overall</span><b>${Math.round(S.health)}%</b></div><div class="row"><span>Fitness</span><b>${S.healthState.fitness}%</b></div><div class="row"><span>Sleep quality</span><b>${S.healthState.sleep}%</b></div><div class="row"><span>Current issue</span><b>${esc(S.healthState.illness||'None')}</b></div></div><div class="card"><h3>Care</h3><div class="action-grid"><button class="action" data-act="healthCheck"><strong>🩺 Checkup</strong><small>Spend $15 and address health concerns.</small></button><button class="action" data-act="therapy"><strong>🧠 Mental wellbeing</strong><small>Work on stress and perspective.</small></button><button class="action" data-act="exercise"><strong>🏃 Exercise</strong><small>Build fitness and reduce stress.</small></button></div></div></div>`}
function careerPanel(){return `<div class="dashboard"><div class="card"><h3>Career</h3><div class="row"><span>Current role</span><b>${esc(S.career.job||'None')}</b></div><div class="row"><span>Skills</span><b>${S.career.skills}</b></div><div class="row"><span>Reputation</span><b>${S.career.reputation}</b></div><div class="action-grid"><button class="action" data-act="careerSkill"><strong>Build a skill</strong><small>Practice something useful for future work.</small></button><button class="action" data-act="applyJob"><strong>Look for work</strong><small>Opportunities depend on age and circumstances.</small></button></div></div><div class="card"><h3>Money</h3><div class="row"><span>Cash</span><b>${money(S.money)}</b></div><div class="row"><span>Savings</span><b>${money(S.finance.savings)}</b></div><div class="row"><span>Investments</span><b>${money(S.finance.investments)}</b></div><div class="action-grid"><button class="action" data-act="saveMoney"><strong>Save $25</strong><small>Move cash into savings.</small></button><button class="action" data-act="invest"><strong>Invest up to $50</strong><small>Adult option; returns are uncertain.</small></button></div></div></div>`}
function worldPanel(){return `<div class="dashboard"><div class="card"><h3>Travel</h3><div class="row"><span>Trips taken</span><b>${S.travel.trips}</b></div><p class="muted-text">Trips cost money and time, and can create chance encounters.</p><button class="action" data-act="tripPlan"><strong>Plan a short trip</strong><small>Transport + time + unpredictable encounters.</small></button></div><div class="card"><h3>Online presence</h3><div class="row"><span>Followers</span><b>${S.social.followers}</b></div><div class="row"><span>Posts</span><b>${S.social.posts}</b></div><div class="row"><span>Reputation</span><b>${S.social.reputation}</b></div><button class="action" data-act="social"><strong>Post / interact</strong><small>Attention can grow slowly or suddenly.</small></button></div></div>`}

function renderPanel(){let html=active==='school'?schoolPanel():active==='people'?peoplePanel():active==='phone'?phonePanel():active==='places'?placesPanel():active==='weather'?weatherPanel():active==='business'?businessPanel():active==='needs'?needsPanel():active==='development'?developmentPanel():active==='family'?familyPanel():active==='health'?healthPanel():active==='career'?careerPanel():active==='world'?worldPanel():homePanel();$('panel-host').innerHTML=html;today()}
function renderNeedsHud(){S.wants=wants();const icons={hunger:'🍽️',hygiene:'🧼',toilet:'🚽',fun:'🎈',social:'👥',comfort:'🏠',sleep:'💤'};$('need-stage').textContent=lifeStage();$('needs-hud').innerHTML=Object.entries(S.needs).map(([k,v])=>{const u=needUrgency(k,v);return `<div class="need-mini ${u>=75?'urgent':''}"><span>${icons[k]||'•'} ${esc(k[0].toUpperCase()+k.slice(1))}</span><b>${needLabel(k,v)}</b><i><em style="width:${clamp(u)}%"></em></i></div>`}).join('');$('wants-hud').innerHTML=S.wants.length?S.wants.map(w=>`<span class="want-pill">${esc(w)}</span>`).join(''):'<span class="muted-text">Content for now</span>'}
function render(){if(!S)return;$('life-name').textContent=S.name;$('life-subtitle').textContent=`Age ${S.age} • Day ${S.day} • ${S.place}`;$('s-age').textContent=S.age;$('s-money').textContent=money(S.money);$('s-health').textContent=Math.round(S.health);$('s-happy').textContent=Math.round(S.happiness);$('s-energy').textContent=Math.round(S.energy);$('s-stress').textContent=Math.round(S.stress);$('s-luck').textContent=Math.round(S.luck)+'%';$('s-mentality').textContent=S.mentality;$('i-place').textContent=S.place;$('i-dob').textContent=S.dob;$('i-zodiac').textContent=S.zodiac;$('i-family').textContent=S.wealth;$('event-meta').textContent=`DAY ${S.day} • AGE ${S.age} • ${S.weather.type.toUpperCase()}`;$('event-title').textContent=S.current.title;$('event-text').textContent=S.current.text;$('event-actions').innerHTML=S.age>=6?`<button data-act="friend">See someone</button>${S.school?'<button data-act="school">Go to school</button>':''}${canUseOwnPhone()?'<button data-act="message">Check phone</button>':''}`:'';$('people').innerHTML=S.people.slice(0,6).map(p=>`<div class="person"><b>${esc(p.name)}</b><small>${esc(p.mood)} • relationship ${p.rel}</small></div>`).join('');const nav=lifeNav();if(!nav.some(x=>x[0]===active))active='home';$('tabs').innerHTML=nav.map(x=>`<button class="side-link ${active===x[0]?'active':''}" data-tab="${x[0]}"><span>${x[1]}</span><b>${x[2]}</b></button>`).join('');renderNeedsHud();renderPanel();$('log').innerHTML=S.log.map(e=>`<div class="log-entry"><div class="log-date">DAY ${e.day} • AGE ${e.age}</div><b>${esc(e.title)}</b><p>${esc(e.text)}</p></div>`).join('')}
function ageUp(){if(!S)return;const days=365;advance(days);S.age++;resolveGiftRequests('Birthday');S.people=makePeople(S.age);schedule(S.age);ensureEvents();developmentalEvents();S.energy=100;S.stress=clamp(S.stress-5);setWeather();log('🎂 Birthday',`You turned ${S.age}. Your household may celebrate with cake, relatives, friends or a quieter family tradition depending on relationships and circumstances.`);if(S.age<=12&&Math.random()<.75)S.familyEvents.unshift({day:S.day,text:`A birthday celebration is being planned for your ${S.age}${S.age===1?'st':S.age===2?'nd':S.age===3?'rd':'th'} birthday.`});S.current={title:`Age ${S.age}`,text:'A full year passed. Not everything important happened on a button you pressed.'};render();save();toast(`Age ${S.age}!`)}
$('tabs').onclick=e=>{const b=e.target.closest('[data-tab]');if(!b)return;active=b.dataset.tab;render()};
$('panel-host').onclick=e=>{const b=e.target.closest('[data-act],[data-exam],[data-person],[data-person-msg],[data-use],[data-buy],[data-set-stall],[data-set-yardsale],[data-yard-negotiate],[data-event-choice]');if(!b)return;if(b.dataset.exam)act('exam',b.dataset.exam);else if(b.dataset.person!==undefined)act('friend',b.dataset.person);else if(b.dataset.personMsg!==undefined)act('messagePerson',b.dataset.personMsg);else if(b.dataset.use)act('useGear',b.dataset.use);else if(b.dataset.buy){const item=b.dataset.buy,c=gearCost(item);if(S.money<c){toast('Not enough money.');return}S.money-=c;S.inventory[item]++;log('Shopping',`You bought ${gearName(item)} for ${money(c)}.`);render();save();return}else if(b.dataset.setStall){if(S.age<16&&S.permissions.stand!==true){requestPermission('stand');render();save();return}setStallItem();return}else if(b.dataset.setYardsale){if(S.age<16&&S.permissions.yardSale!==true){requestPermission('yardSale');render();save();return}S.stall={active:true,type:'Yard Sale',items:[{name:'Used household items',cost:0,price:10,stock:6,quality:60}],revenue:0,visitors:0,day:S.day,exaggeration:20};log('Yard sale','You put selected belongings out for sale. Buyers can bargain and you can decide whether to accept.');render();save();return}else if(b.dataset.yardNegotiate){act('negotiate');return}else if(b.dataset.eventChoice){act('eventChoice',b.dataset.eventChoice);return}else act(b.dataset.act,b.dataset.arg||b.dataset.subject)};
$('event-actions').onclick=e=>{const b=e.target.closest('[data-act]');if(b)act(b.dataset.act)};$('age-up').onclick=ageUp;
$('begin').onclick=()=>{try{S=makeState();enterGame()}catch(err){console.error(err);const box=$('creator-error');box.hidden=false;box.textContent='Could not start life: '+(err?.message||err);}};$('save').onclick=save;$('export').onclick=exportSave;$('load-last').onclick=()=>{const x=localStorage.getItem(KEY);if(!x){toast('No autosave found');return}try{S=JSON.parse(x);migrate();enterGame()}catch{toast('Autosave is invalid')}};$('import-btn').onclick=importFile;$('menu-import').onclick=importFile;$('menu-save').onclick=save;$('menu-export').onclick=exportSave;$('clear-log').onclick=()=>{if(S){S.log=[];render();save()}};$('menu-new').onclick=()=>{S=null;localStorage.removeItem(KEY);$('overlay').classList.add('hidden');$('game').classList.add('hidden');$('creator').classList.remove('hidden')};$('pause').onclick=()=>$('overlay').classList.remove('hidden');$('close-menu').onclick=()=>$('overlay').classList.add('hidden');document.addEventListener('keydown',e=>{if(e.key==='Escape')$('overlay').classList.toggle('hidden')});
function enterGame(){migrate();schedule(S.age);ensureEvents();if(!S.log.length)log('Life begins',S.current.text);$('creator').classList.add('hidden');$('game').classList.remove('hidden');render();save()}
setInterval(()=>{if(S)save()},30000);if(new URLSearchParams(location.search).get('smoke')==='1'){setTimeout(()=>{try{$('begin').click();document.body.dataset.smoke=(!$('game').classList.contains('hidden')&&S)?'pass':'fail'}catch(e){document.body.dataset.smoke='fail';document.body.dataset.smokeError=e.message}},0)}
})();
