(()=>{'use strict';
const $=id=>document.getElementById(id), clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,Number(n)||0)), money=n=>'$'+Math.round(n).toLocaleString();
const KEY='lifeSim_v4_livingWorld';
const personalities=['Kind','Ambitious','Curious','Calm','Bold','Funny','Romantic','Practical','Creative','Competitive','Shy','Social','Stubborn','Empathetic','Independent','Adventurous'];
const talents=['Music','Writing','Art','Sports','Math','Science','Programming','Business','Languages','Acting','Fashion','Cooking','Photography','Gaming','Leadership','Dance'];
const names=['Mina','Lena','Sofia','Emma','Ari','Nora','Maya','Iris','Lina','Elena','Avery','Jade','Theo','Noah','Leo','Eli','Kai','Lucas','Julian','Alex'];
const places=['Ho Chi Minh City, Vietnam','Seoul, South Korea','Tokyo, Japan','London, UK','Paris, France','New York City, USA','Vancouver, Canada','Singapore','Bangkok, Thailand','Sydney, Australia'];
const weatherTypes=['Sunny','Cloudy','Rainy','Stormy','Cool','Hot','Windy'];
const moods=['good','busy','quiet','excited','stressed','curious','tired','happy'];
let mode='custom',S=null,active='home',selectedP=[],selectedT=[];
const rand=a=>a[Math.floor(Math.random()*a.length)], esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(t){const x=$('toast');x.textContent=t;x.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>x.classList.remove('show'),1800)}
function chips(id,list,sel){$(id).innerHTML=list.map(x=>`<button type="button" class="chip ${sel.includes(x)?'selected':''}" data-chip="${esc(x)}">${esc(x)}</button>`).join('')}
chips('personality',personalities,selectedP);chips('talents',talents,selectedT);
$('personality').onclick=e=>{const b=e.target.closest('[data-chip]');if(!b)return;const v=b.dataset.chip;if(selectedP.includes(v))selectedP=selectedP.filter(x=>x!==v);else if(selectedP.length<5)selectedP.push(v);chips('personality',personalities,selectedP)};
$('talents').onclick=e=>{const b=e.target.closest('[data-chip]');if(!b)return;const v=b.dataset.chip;if(selectedT.includes(v))selectedT=selectedT.filter(x=>x!==v);else if(selectedT.length<5)selectedT.push(v);chips('talents',talents,selectedT)};
document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('.mode').forEach(x=>x.classList.toggle('active',x===b));if(mode!=='custom')randomize(false)});
function randomize(all=true){$('c-name').value=rand(names);$('c-place').value=rand(places);$('c-gender').value=rand(['Girl','Boy','Non-binary','Other']);$('c-attraction').value=rand(['Men','Women','All genders','Not sure yet','Asexual / romantic']);$('c-wealth').value=rand(['Struggling','Modest','Middle class','Comfortable','Wealthy']);$('c-home').value=rand(['Warm and stable','Busy but loving','Strict','Chaotic','Quiet','Highly privileged','Unpredictable']);$('c-dob').value=`${1998+Math.floor(Math.random()*15)}-${String(1+Math.floor(Math.random()*12)).padStart(2,'0')}-${String(1+Math.floor(Math.random()*27)).padStart(2,'0')}`;selectedP=[rand(personalities),rand(personalities)];selectedT=[rand(talents),rand(talents)];chips('personality',personalities,selectedP);chips('talents',talents,selectedT);if(all)toast('Character randomized')}
document.querySelectorAll('[data-random]').forEach(b=>b.onclick=()=>randomize(true));$('random-all').onclick=()=>randomize(true);
function mentalityFor(personality){const map={Calm:'Steady',Bold:'Bold',Ambitious:'Driven',Curious:'Curious',Funny:'Playful',Romantic:'Romantic',Competitive:'Competitive',Shy:'Reserved',Social:'Social',Independent:'Independent',Empathetic:'Empathetic'};return map[(personality||[])[0]]||'Balanced'}
function makePeople(age){const base=age<6?['Mom','Dad','Grandmother']:age<13?['Mom','Dad','Mia • classmate','Noah • neighbor']:age<18?['Mom','Dad','Mia • best friend','Noah • classmate','Jade • club member','Leo • crush']:['Mom','Dad','Mia • old friend','Noah • colleague','Jade • friend','Leo • connection'];return base.map((name,i)=>({name,rel:clamp(72-i*8+Math.floor(Math.random()*12)),memory:'A small shared memory waiting to be discovered.',mood:rand(moods),lastSeen:1+Math.floor(Math.random()*8),secretChance:Math.random()}))}
function initialWeather(){return {type:rand(weatherTypes),temp:20+Math.floor(Math.random()*17),humidity:40+Math.floor(Math.random()*50),forecast:[]}}
function makeState(){const personality=selectedP.length?[...selectedP]:[rand(personalities)], talentsNow=selectedT.length?[...selectedT]:[rand(talents)];return {version:4,name:$('c-name').value.trim()||rand(names),dob:$('c-dob').value||'2010-01-01',place:$('c-place').value.trim()||rand(places),zodiac:$('c-zodiac').value==='auto'?'Unknown':$('c-zodiac').value,gender:$('c-gender').value,attraction:$('c-attraction').value,wealth:$('c-wealth').value,home:$('c-home').value,personality,talents:talentsNow,age:0,day:1,money:['Struggling','Modest'].includes($('c-wealth').value)?80:300,health:100,happiness:70,energy:100,stress:10,luck:clamp(35+Math.random()*30),mentality:mentalityFor(personality),gpa:null,school:null,people:makePeople(0),log:[],events:[],exams:[],messages:[],flags:{},weather:initialWeather(),inventory:{umbrella:0,raincoat:0,sweater:0,firewood:0,sunglasses:0,waterBottle:0},stall:null,finance:{savings:0,debt:0,investments:0},career:{job:null,reputation:0,skills:0},healthState:{fitness:50,sleep:70,illness:null},social:{followers:0,reputation:50,posts:0},romance:{status:'Single',partner:null,history:[]},travel:{trips:0,lastTrip:null},family:{closeness:65,tension:10},current:{title:'Welcome to the world.',text:'Your story is beginning. Your family, neighborhood and future are already moving around you.'}}}
function log(title,text){S.log.unshift({day:S.day,age:S.age,title,text});if(S.log.length>350)S.log.pop()}
function save(){if(!S)return;localStorage.setItem(KEY,JSON.stringify(S));$('save-status').textContent='Saved '+new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}
function exportSave(){if(!S)return;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(S,null,2)],{type:'application/json'}));a.download=`life-${S.name.replace(/\s+/g,'-')}.json`;a.click();URL.revokeObjectURL(a.href)}
function importFile(){$('import-file').click()}
$('import-file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{S=JSON.parse(await f.text());migrate();enterGame();toast('Save imported')}catch{toast('Invalid save file')}};
function migrate(){S.version=4;S.luck=clamp(S.luck??50);S.mentality=S.mentality||'Balanced';S.weather=S.weather||initialWeather();S.inventory=Object.assign({umbrella:0,raincoat:0,sweater:0,firewood:0,sunglasses:0,waterBottle:0},S.inventory||{});S.messages=S.messages||[];S.exams=S.exams||[];S.events=S.events||[];S.log=S.log||[];S.stall=S.stall||null;S.people=S.people||makePeople(S.age||0);S.finance=Object.assign({savings:0,debt:0,investments:0},S.finance||{});S.career=Object.assign({job:null,reputation:0,skills:0},S.career||{});S.healthState=Object.assign({fitness:50,sleep:70,illness:null},S.healthState||{});S.social=Object.assign({followers:0,reputation:50,posts:0},S.social||{});S.romance=Object.assign({status:'Single',partner:null,history:[]},S.romance||{});S.travel=Object.assign({trips:0,lastTrip:null},S.travel||{});S.family=Object.assign({closeness:65,tension:10},S.family||{})}
function schedule(age){if(S.school&&S.school.grade&&S.age===age&&S.exams&&S.exams.length)return;if(age>=6&&age<=18){S.exams=[];const subs=['Mathematics','English','Literature','Science','History','Computer Science'];subs.forEach((subject,i)=>S.exams.push({subject,days:4+i*5,score:null,type:i%3===0?'Midterm':i%3===1?'Quiz':'Final'}));S.school={name:rand(['Riverside Academy','Central International School','Westside High','Sunrise Secondary School']),grade:age<=11?'Primary':age<=14?'Middle school':'High school',className:`${age}-${String.fromCharCode(65+Math.floor(Math.random()*4))}`,attendance:96,gpa:S.gpa??(2.8+Math.random()*1.1),rank:Math.floor(8+Math.random()*25),subjects:subs.map((x,i)=>({name:x,score:72+Math.floor(Math.random()*24),trend:i%2?'→':'↑'})),clubs:[],contests:[]}}else S.school=null}
function setWeather(){const old=S.weather?.type;let type=rand(weatherTypes);if(old&&Math.random()<.35)type=old;const ranges={Sunny:[24,35],Cloudy:[20,31],Rainy:[19,29],Stormy:[18,28],Cool:[14,23],Hot:[30,39],Windy:[19,30]};const r=ranges[type];S.weather={type,temp:r[0]+Math.floor(Math.random()*(r[1]-r[0]+1)),humidity:40+Math.floor(Math.random()*55),forecast:Array.from({length:5},()=>{const t=rand(weatherTypes),rr=ranges[t];return {type:t,temp:rr[0]+Math.floor(Math.random()*(rr[1]-rr[0]+1))}})}}
function weatherAdvice(){const w=S.weather.type;if(['Rainy','Stormy'].includes(w))return 'Rain gear helps outdoors; staying in can be more comfortable.';if(w==='Hot')return 'Heat increases thirst and fatigue; water, shade and A/C matter.';if(w==='Cool')return 'A sweater or warmer room helps comfort.';if(w==='Sunny')return 'Sunglasses, water and sunscreen are useful outside.';return 'The weather is mild enough for most plans.'}
function ensureEvents(){S.events=[];if(S.age>=6&&S.age<=18)S.events.push({kind:'school',title:'School day',text:'Classes, teachers, classmates and unscheduled moments are waiting.'});if(S.age>=13)S.events.push({kind:'social',title:'Your social world is changing',text:'People remember what happens between you, not just a relationship score.'});S.events.push({kind:'world',title:'Life keeps moving',text:'Someone nearby is making a decision that may or may not cross your path.'})}
function advance(days){for(let d=0;d<days;d++){S.day++;S.energy=clamp(S.energy-2);S.stress=clamp(S.stress+(Math.random()<.15?2:-1));S.happiness=clamp(S.happiness+(Math.random()-.48)*2);S.exams.forEach(x=>x.days--);if(S.day%7===0){setWeather();worldTick();}if(S.stall?.active)stallTick()}if(days>0&&Math.random()<.65)randomLifeEvent()}
function worldTick(){S.people.forEach(p=>{p.rel=clamp(p.rel+(Math.random()<.52?1:-1));p.mood=rand(moods);p.lastSeen++;if(Math.random()<.08){p.memory='Something changed in their life while you were elsewhere.';log('Someone else’s life',`${p.name} had a change you were not directly involved in.`)}});if(S.school)S.school.subjects.forEach(s=>{s.score=clamp(s.score+(Math.random()<.45?1:-1),0,100)});if(Math.random()<.2)S.luck=clamp(S.luck+(Math.random()<.5?-1:1))}
function randomLifeEvent(){const pool=[];if(S.age<6)pool.push(['Family moment','A family member does something ordinary that becomes part of your early memories.']);if(S.age>=6&&S.age<=18)pool.push(['Unexpected school moment','A teacher changes the plan for the day. A classmate reacts strongly.'],['New school opportunity','Someone mentions a club, contest or activity you could join.']);if(S.age>=13)pool.push(['New message','Someone you know sends a message you did not expect.'],['Social ripple','You hear two different versions of the same story about someone you know.']);pool.push(['Neighborhood life','A nearby family is celebrating, moving, arguing, renovating or simply changing their routine.'],['Small coincidence','A normal trip puts you in the same place as someone from another part of your life.']);if(S.weather.type==='Rainy')pool.push(['Rainy-day coincidence','The rain changes everyone’s plans. Someone you know ends up somewhere unexpected.']);const e=rand(pool);S.current={title:e[0],text:e[1]};log(e[0],e[1]);S.events.unshift({kind:'popup',title:e[0],text:e[1],day:S.day,choices:['Look into it','Let it pass']});if(S.events.length>12)S.events.pop()}
function luckyRoll(base=0){return clamp(base+(Math.random()*100<S.luck?10:0)+(Math.random()*100<S.luck?5:0),0,100)}
function act(id,arg){if(!S)return;
if(id==='study'){if(!S.school){toast('There is no current school schedule.');return}const sub=S.school.subjects.find(s=>s.name===arg)||rand(S.school.subjects);S.energy=clamp(S.energy-12);S.stress=clamp(S.stress+3);sub.score=clamp(sub.score+2+Math.floor(Math.random()*3));log('Study session',`You focused on ${sub.name}. Your current score moved to ${sub.score}.`)}
else if(id==='exam'){const x=S.exams.find(e=>e.subject===arg);if(!x)return;if(x.days>0){toast(`The ${x.subject} exam is in ${x.days} days.`);return}const sub=S.school.subjects.find(s=>s.name===x.subject);x.score=clamp(Math.round(sub.score+(Math.random()-.25)*18+(S.luck-50)/5),0,100);log(`${x.subject} exam`,x.score>=70?`You finished with ${x.score}%.`:`The exam was difficult. You scored ${x.score}%.`);S.stress=clamp(S.stress+8);S.happiness=clamp(S.happiness+(x.score>=70?4:-3))}
else if(id==='school'){S.school?.attendance&&(S.school.attendance=clamp(S.school.attendance+.1));S.energy=clamp(S.energy-8);log('School','You attend classes. Something useful, awkward, funny or strange may happen between lessons.');if(Math.random()<.3)randomLifeEvent()}
else if(id==='friend'){const chosen=Number.isInteger(Number(arg))?S.people[Number(arg)]:null;const pool=S.people.filter(x=>!['Mom','Dad','Grandmother'].includes(x.name));const p=chosen||rand(pool.length?pool:S.people);p.rel=clamp(p.rel+6);p.memory='You spent time together today.';p.lastSeen=0;S.happiness=clamp(S.happiness+5);log('Time with '+p.name,`You made a new memory together. ${p.name} seems ${p.mood}.`)}
else if(id==='messagePerson'){const p=S.people[Number(arg)]||rand(S.people);S.messages.unshift({from:p.name,text:'You reached out first. They replied and the conversation is now open.',day:S.day,read:true});p.rel=clamp(p.rel+2);log('Message to '+p.name,'You started a conversation.');}
else if(id==='message'){const p=rand(S.people);S.messages.unshift({from:p.name,text:rand(['Are you around later?','I need to tell you something.','Did you hear what happened?','Want to do something this weekend?']),day:S.day,read:false});log('New message',`${p.name} sent you a message.`)}
else if(id==='reply'){const m=S.messages.find(x=>!x.read)||S.messages[0];if(m){m.read=true;const p=S.people.find(x=>x.name===m.from);if(p)p.rel=clamp(p.rel+4);log('Conversation',`You replied to ${m.from}. The conversation continues outside your control.`)}}
else if(id==='walk'){S.energy=clamp(S.energy-6);S.happiness=clamp(S.happiness+5);if(['Rainy','Stormy'].includes(S.weather.type)&&!S.inventory.umbrella&&!S.inventory.raincoat){S.health=clamp(S.health-3);log('Caught in the rain','You went outside without rain protection and came back soaked.')}else log('Out and about',`You went outside in ${S.weather.type.toLowerCase()} weather. ${weatherAdvice()}`)}
else if(id==='exercise'){S.energy=clamp(S.energy-14);S.health=clamp(S.health+3);S.stress=clamp(S.stress-4);log('Exercise','You worked out. Your body feels different for the rest of the day.')}
else if(id==='sleep'){S.energy=clamp(S.energy+55);S.stress=clamp(S.stress-12);advance(1);log('Sleep','You slept and woke up to a new day.')}
else if(id==='meal'){S.energy=clamp(S.energy+15);S.health=clamp(S.health+1);log('Meal','You ate. Food, timing and routine quietly shape your day.')}
else if(id==='family'){const p=rand(S.people.filter(x=>['Mom','Dad','Grandmother'].includes(x.name))||S.people);p.rel=clamp(p.rel+4);p.memory='You had a family moment today.';log('Family time',`You spent time with ${p.name}.`)}
else if(id==='shower'){S.happiness=clamp(S.happiness+2);log('Getting ready','You took care of yourself and reset for the day.')}
else if(id==='dress'){log('Style choice','You chose what to wear. Your style can influence how people read a situation, but it never determines it.')}
else if(id==='useGear'){const item=arg;if(S.inventory[item]>0){S.inventory[item]--;log('Used '+gearName(item),gearUse(item))}else toast('You do not own that item.')}
else if(id==='homeComfort'){const item=arg;log('Home comfort',gearUse(item));if(item==='ac')S.energy=clamp(S.energy+3);if(item==='fan')S.stress=clamp(S.stress-3);if(item==='fireplace')S.happiness=clamp(S.happiness+4)}
else if(id==='travel'){S.money=Math.max(0,S.money-20);S.energy=clamp(S.energy-15);log('Travel','You went somewhere new. A trip can create opportunities, expenses or people you never expected.')}
else if(id==='work'){if(S.age<16){toast('Local rules usually limit regular paid work before the mid-teens.');return}const pay=20+Math.floor(S.luck/5)+Math.floor(Math.random()*25);S.money+=pay;S.energy=clamp(S.energy-20);log('Work shift',`You earned ${money(pay)}. The job also introduced you to another slice of everyday life.`)}
else if(id==='business'){if(S.age<8){toast('You are too young for this kind of independent selling right now.');return}active='business';log('Business idea','You started thinking like a seller: what to offer, who needs it, and what they will actually pay.');}
else if(id==='startStall'){startStall()}
else if(id==='stallSale'){runStall()}
else if(id==='club'){if(S.school){const c=rand(['Art Club','Debate','Science Club','Football','Drama','Coding','Music','Photography']);if(!S.school.clubs.includes(c))S.school.clubs.push(c);log('Club','You explored '+c+'. New people and opportunities can grow from this.')}}
else if(id==='contest'){if(S.school){const c=rand(['Math Olympiad','Science Fair','Debate Tournament','Art Showcase','Coding Challenge','School Sports Meet']);S.school.contests.push({name:c,status:'Considering'});log('Contest opportunity',`A ${c} opportunity appeared. You can decide whether it is worth your time.`)}}
else if(id==='social'){S.social.posts++;const gain=Math.max(0,Math.floor(Math.random()*8+(S.luck-50)/15));S.social.followers+=gain;log('Social feed',`You posted or interacted online. ${gain?gain+' new people followed you.':'It was a quiet post.'}`);if(Math.random()<.35)act('message')}
else if(id==='healthCheck'){S.money=Math.max(0,S.money-15);S.health=clamp(S.health+5);S.healthState.illness=null;log('Health check','You checked in on your health and addressed small problems before they grew.')}
else if(id==='therapy'){S.money=Math.max(0,S.money-20);S.stress=clamp(S.stress-18);S.happiness=clamp(S.happiness+5);log('Mental wellbeing','You spent time working through stress and perspective.')}
else if(id==='careerSkill'){S.career.skills++;S.energy=clamp(S.energy-10);log('Skill building',`You practiced a career skill. Skill level is now ${S.career.skills}.`)}
else if(id==='applyJob'){if(S.age<16){toast('Regular paid jobs unlock later in the teen years.');return}S.career.job=rand(['Cafe assistant','Retail associate','Tutor','Junior creator','Office assistant']);log('New job',`You were offered work as a ${S.career.job}.`)}
else if(id==='saveMoney'){const amount=Math.min(S.money,25);S.money-=amount;S.finance.savings+=amount;log('Savings',`You moved ${money(amount)} into savings.`)}
else if(id==='invest'){if(S.age<18){toast('Investing is available in adulthood in this simulation.');return}const amount=Math.min(S.money,50);S.money-=amount;S.finance.investments+=amount;log('Investment',`You invested ${money(amount)}. Its future value is uncertain.`)}
else if(id==='familyTalk'){S.family.closeness=clamp(S.family.closeness+4);S.family.tension=clamp(S.family.tension-2);log('Family conversation','You had a real conversation at home. It may shape how family members respond later.')}
else if(id==='romance'){if(S.age<13){toast('Romantic storylines become available in the teen years.');return}const candidates=S.people.filter(p=>!['Mom','Dad','Grandmother'].includes(p.name));const p=rand(candidates);if(!p)return;S.romance.history.push({day:S.day,age:S.age,name:p.name,event:'A spark or possibility appeared.'});p.rel=clamp(p.rel+3);log('A possibility',`A moment with ${p.name} felt different. Nothing is guaranteed from here.`)}
else if(id==='tripPlan'){const cost=40+Math.floor(Math.random()*80);if(S.money<cost){toast('This trip costs more than you have available.');return}S.money-=cost;S.travel.trips++;S.travel.lastTrip='Day '+S.day;advance(2);log('Trip',`You spent ${money(cost)} on transport and a short trip. New surroundings created new possibilities.`)}
else if(id==='negotiate'){if(!S.stall?.active){toast('Open a stand or yard sale first.');return}const item=S.stall.items[0],offer=Math.max(1,Math.round(item.price*(.55+Math.random()*.35)));const accepted=Math.random()*100 < 45+(S.luck-50)/4;if(accepted&&item.stock>0){item.stock--;S.money+=offer;S.stall.revenue+=offer;log('Negotiation',`A buyer offered ${money(offer)} for ${item.name}. You negotiated and closed the sale.`)}else log('Negotiation',`A buyer offered ${money(offer)} for ${item.name}, but the deal fell through. Walking away can be part of selling.`)}
else if(id==='eventChoice'){log('Event choice',arg==='Look into it'?'You decided the unexpected thing was worth your attention.':'You let it pass and continued with your own day.');S.events=S.events.filter(e=>e.kind!=='popup')}
render();save()}
function gearCost(i){return {umbrella:12,raincoat:28,sweater:24,firewood:10,sunglasses:18,waterBottle:15}[i]||10}
function gearName(i){return {umbrella:'Umbrella',raincoat:'Raincoat',sweater:'Sweater',firewood:'Firewood',sunglasses:'Sunglasses',waterBottle:'Water bottle'}[i]||i}
function gearUse(i){return {umbrella:'You stayed drier under your umbrella.',raincoat:'Your raincoat kept the rain from ruining your plans.',sweater:'The sweater kept you warmer.',fireplace:'The fireplace made home warmer and calmer.',ac:'You cooled the room with A/C.',fan:'You cooled down with a fan.',sunglasses:'Your sunglasses made the bright weather easier on your eyes.',waterBottle:'You drank water and felt better prepared for the heat.'}[i]||'You used it.'}
function startStall(){if(S.stall?.active){toast('Your stall is already open.');return}S.stall={active:true,type:'Lemonade',items:[{name:'Lemonade',cost:2,price:5,stock:8,quality:70}],revenue:0,visitors:0,day:S.day,exaggeration:30};log('Small business','You set up a small selling stand. What you choose to sell, price, presentation and negotiation can change the outcome.')}
function runStall(){if(!S.stall?.active){startStall();return}let st=S.stall;let item=st.items[0];if(item.stock<=0){toast('You are sold out.');st.active=false;return}let buyers=1+Math.floor(Math.random()*4),sold=0,revenue=0;for(let i=0;i<buyers&&item.stock>0;i++){const demand=clamp(65+(item.quality-50)/2-(item.price-4)*10+(st.exaggeration-30)/4+(S.luck-50)/3,5,95);if(Math.random()*100<demand){item.stock--;sold++;revenue+=item.price}}st.revenue+=revenue;st.visitors+=buyers;S.money+=revenue;log('Stand sales',`You had ${buyers} visitors, sold ${sold} ${item.name}, and earned ${money(revenue)}. Some buyers negotiated; others simply walked away.`);if(item.stock===0)st.active=false}
function stallTick(){if(Math.random()<.55)runStall()}
function setStallItem(){const name=$('stall-item')?.value.trim()||'Homemade item',price=Math.max(1,Number($('stall-price')?.value)||5),stock=Math.max(1,Math.floor(Number($('stall-stock')?.value)||5)),quality=clamp(Number($('stall-quality')?.value)||70),ex=clamp(Number($('stall-exaggeration')?.value)||30);S.stall=S.stall||{active:true,revenue:0,visitors:0,day:S.day};S.stall.active=true;S.stall.items=[{name,cost:Math.max(0.2,price*.35),price,stock,quality}];S.stall.exaggeration=ex;log('Stand prepared',`You chose to sell ${name} at ${money(price)} each, with ${stock} available and a ${ex}% exaggeration level in your pitch.`);render();save()}
function today(){const arr=[];if(S.weather)arr.push(`<div class="row"><span>Weather</span><b>${esc(S.weather.type)} ${S.weather.temp}°C</b></div>`);const next=S.exams.filter(x=>x.score==null).sort((a,b)=>a.days-b.days)[0];if(next)arr.push(`<div class="row"><span>${esc(next.subject)}</span><b>${next.days<=0?'TODAY':next.days+' days'}</b></div>`);const unread=S.messages.filter(x=>!x.read).length;if(unread)arr.push(`<div class="row"><span>Unread messages</span><b>${unread}</b></div>`);if(S.stall?.active)arr.push(`<div class="row"><span>Open stand</span><b>${S.stall.items?.[0]?.stock||0} left</b></div>`);$('today-list').innerHTML=arr.join('')||'<p class="muted-text">Nothing urgent.</p>'}
function schoolPanel(){if(!S.school)return `<div class="dashboard"><div class="card wide"><h3>No school right now</h3><p class="muted-text">School becomes a living system during school-age years.</p></div></div>`;return `<div class="dashboard"><div class="card"><h3>${esc(S.school.name)}</h3><p>${S.school.grade} • Class ${S.school.className}</p><div class="row"><span>GPA</span><b>${S.school.gpa.toFixed(2)}</b></div><div class="row"><span>Class rank</span><b>#${S.school.rank}</b></div><div class="row"><span>Attendance</span><b>${S.school.attendance.toFixed(1)}%</b></div></div><div class="card"><h3>Clubs & contests</h3><p class="muted-text">${S.school.clubs.length?S.school.clubs.join(' • '):'No club commitments yet.'}</p><div class="action-grid"><button class="action" data-act="club"><strong>Explore clubs</strong><small>Meet people and discover interests</small></button><button class="action" data-act="contest"><strong>Find contests</strong><small>Auditions, teams and competitions</small></button></div>${S.school.contests.map(c=>`<div class="row"><span>${esc(c.name)}</span><span class="tag">${esc(c.status)}</span></div>`).join('')}</div><div class="card wide"><h3>Subjects & academic scores</h3><div class="list">${S.school.subjects.map(s=>`<div class="row"><span style="min-width:60%"><b>${esc(s.name)}</b> <span class="tag">${s.trend}</span><div class="progress"><i style="width:${s.score}%"></i></div><button class="small" data-act="study" data-subject="${esc(s.name)}">Study this subject</button></span><b>${s.score}</b></div>`).join('')}</div></div><div class="card wide"><h3>Exam countdown & reminders</h3><div class="list">${S.exams.map(x=>`<div class="row"><span><b>${esc(x.subject)}</b><br><span class="muted-text">${x.type}</span></span><span class="countdown">${x.score!=null?'Score '+x.score:(x.days<=0?'TODAY':x.days+' days')}</span>${x.score==null&&x.days<=0?`<button class="small" data-exam="${esc(x.subject)}">Take exam</button>`:''}</div>`).join('')}</div></div></div>`}
function peoplePanel(){return `<div class="dashboard"><div class="card wide"><h3>People have lives outside you</h3><p class="muted-text">NPCs change while you are elsewhere. Their routines, moods, relationships and memories can create future encounters.</p></div>${S.people.map((p,i)=>`<div class="card"><h3>${esc(p.name)}</h3><p><span class="tag">${esc(p.mood)}</span> Relationship ${p.rel}</p><div class="progress"><i style="width:${p.rel}%"></i></div><p class="muted-text">Memory: ${esc(p.memory)}</p><p class="muted-text">Last seen ${p.lastSeen} day${p.lastSeen===1?'':'s'} ago.</p><div class="action-grid"><button class="action" data-person="${i}"><strong>Spend time</strong><small>Create a specific memory</small></button><button class="action" data-person-msg="${i}"><strong>Message</strong><small>Start a conversation</small></button></div></div>`).join('')}</div>`}
function phonePanel(){return `<div class="dashboard"><div class="card"><h3>Messages</h3><div class="list">${S.messages.length?S.messages.slice(0,8).map(m=>`<div class="row"><span><b>${esc(m.from)}</b><br>${esc(m.text)}</span><span class="tag">${m.read?'read':'new'}</span></div>`).join(''):'<p class="muted-text">No messages. People are living their own day.</p>'}</div><button class="action" data-act="reply"><strong>Reply to a conversation</strong><small>Messages can become plans, misunderstandings or memories.</small></button></div><div class="card"><h3>Social world</h3><div class="action-grid"><button class="action" data-act="social"><strong>Open social feed</strong><small>Posts, stories, invitations and rumors</small></button><button class="action" data-act="message"><strong>Reach out</strong><small>Send a message to someone</small></button></div></div></div>`}
function weatherPanel(){const w=S.weather;return `<div class="dashboard"><div class="card"><h3>Today's weather</h3><div class="weather-big">${weatherIcon(w.type)} ${esc(w.type)} • ${w.temp}°C</div><p class="muted-text">Humidity ${w.humidity}%</p><p>${weatherAdvice()}</p></div><div class="card"><h3>5-day forecast</h3>${w.forecast.map((x,i)=>`<div class="row"><span>Day ${i+1}</span><b>${weatherIcon(x.type)} ${esc(x.type)} ${x.temp}°C</b></div>`).join('')}</div><div class="card"><h3>What to carry</h3><div class="action-grid">${[['umbrella','☂️ Umbrella'],['raincoat','🧥 Raincoat'],['sweater','🧶 Sweater'],['sunglasses','🕶️ Sunglasses'],['waterBottle','💧 Water bottle']].map(([i,n])=>`<button class="action" data-use="${i}"><strong>${n}</strong><small>Owned: ${S.inventory[i]}</small></button>`).join('')}</div><div class="gear-shop">${[['umbrella','☂️ Umbrella'],['raincoat','🧥 Raincoat'],['sweater','🧶 Sweater'],['firewood','🪵 Firewood'],['sunglasses','🕶️ Sunglasses'],['waterBottle','💧 Water bottle']].map(([i,n])=>`<button class="action" data-buy="${i}"><strong>${n} — ${money(gearCost(i))}</strong><small>Owned: ${S.inventory[i]}</small></button>`).join('')}</div></div><div class="card"><h3>At home</h3><div class="action-grid"><button class="action" data-act="homeComfort" data-arg="fireplace"><strong>🔥 Fireplace</strong><small>${S.inventory.firewood} firewood</small></button><button class="action" data-act="homeComfort" data-arg="ac"><strong>❄️ A/C</strong><small>Cool the room</small></button><button class="action" data-act="homeComfort" data-arg="fan"><strong>🌀 Fan</strong><small>Cool down without A/C</small></button></div></div></div>`}
function weatherIcon(w){return {Sunny:'☀️',Cloudy:'☁️',Rainy:'🌧️',Stormy:'⛈️',Cool:'🌫️',Hot:'🔥',Windy:'💨'}[w]||'🌤️'}
function businessPanel(){const st=S.stall;return `<div class="dashboard"><div class="card wide"><h3>Small business & street selling</h3><p class="muted-text">Choose what to sell, set the price, control stock and decide how much to exaggerate. Buyers have budgets, preferences and willingness to negotiate.</p></div><div class="card"><h3>Set up a stand</h3><label>What are you selling<input id="stall-item" value="${esc(st?.items?.[0]?.name||'Lemonade')}" placeholder="Lemonade, cookies, toys..." /></label><label>Price each<input id="stall-price" type="number" min="1" value="${st?.items?.[0]?.price||5}" /></label><label>Stock<input id="stall-stock" type="number" min="1" value="${st?.items?.[0]?.stock||8}" /></label><label>Quality<input id="stall-quality" type="range" min="1" max="100" value="${st?.items?.[0]?.quality||70}" /></label><label>Exaggerate your pitch<input id="stall-exaggeration" type="range" min="0" max="100" value="${st?.exaggeration||30}" /></label><button class="action" data-set-stall="1"><strong>Open / update stand</strong><small>Then visitors arrive over time.</small></button></div><div class="card"><h3>Today's stand</h3>${st?`<div class="row"><span>Visitors</span><b>${st.visitors}</b></div><div class="row"><span>Revenue</span><b>${money(st.revenue)}</b></div><div class="row"><span>Status</span><b>${st.active?'OPEN':'CLOSED'}</b></div><button class="action" data-act="stallSale"><strong>Work the stand</strong><small>Talk to buyers, negotiate and sell.</small></button>`:'<p class="muted-text">No stand yet.</p>'}</div><div class="card wide"><h3>Yard sale ideas</h3><div class="action-grid"><button class="action" data-set-yardsale="1"><strong>Open a yard sale</strong><small>Choose old clothes, toys, books, electronics or household items.</small></button><button class="action" data-yard-negotiate="1"><strong>Practice negotiation</strong><small>Learn when to hold your price and when to accept.</small></button></div></div></div>`}
function placesPanel(){return `<div class="dashboard"><div class="card"><h3>Home</h3><div class="action-grid"><button class="action" data-act="meal"><strong>🍲 Eat / make food</strong><small>Meals, routines and family moments</small></button><button class="action" data-act="family"><strong>🏠 Family</strong><small>Talk, help, argue, reconnect</small></button><button class="action" data-act="shower"><strong>🚿 Get ready</strong><small>Shower and personal routine</small></button><button class="action" data-act="dress"><strong>👗 Dress & style</strong><small>Clothing and presentation</small></button></div></div><div class="card"><h3>Outside</h3><div class="action-grid"><button class="action" data-act="walk"><strong>🚶 Go outside</strong><small>Weather, parks, streets and chance encounters</small></button><button class="action" data-act="travel"><strong>✈️ Travel</strong><small>Trips, transport and unfamiliar people</small></button></div></div><div class="card"><h3>Body & wellbeing</h3><div class="action-grid"><button class="action" data-act="exercise"><strong>🏃 Exercise</strong><small>Fitness, stress and health</small></button><button class="action" data-act="sleep"><strong>🛏️ Sleep</strong><small>Recover and move into tomorrow</small></button></div></div><div class="card"><h3>Earn & build</h3><div class="action-grid"><button class="action" data-act="work"><strong>💼 Work</strong><small>Paid work when age/location allow</small></button><button class="action" data-act="business"><strong>🥤 Start a small business</strong><small>Lemonade, baking, reselling, yard sales</small></button></div></div></div>`}
function homePanel(){const urgent=S.events.filter(e=>e.kind==='popup').slice(0,3);return `<div class="dashboard"><div class="card wide"><h3>What's happening?</h3><div class="event-card card"><b>${esc(S.current.title)}</b><p class="muted-text">${esc(S.current.text)}</p></div>${urgent.map(e=>`<div class="event-card card"><b>${esc(e.title)}</b><p class="muted-text">${esc(e.text)}</p><div class="event-actions"><button data-event-choice="Look into it">Look into it</button><button data-event-choice="Let it pass">Let it pass</button></div></div>`).join('')}</div><div class="card"><h3>Today</h3><div class="row"><span>Weather</span><b>${weatherIcon(S.weather.type)} ${S.weather.temp}°C</b></div><div class="row"><span>Luck</span><b>${Math.round(S.luck)}%</b></div><div class="row"><span>Mentality</span><b>${esc(S.mentality)}</b></div></div><div class="card"><h3>Contextual actions</h3><div class="action-grid">${quickActions().map(x=>`<button class="action" data-act="${x[0]}"><strong>${x[1]}</strong><small>${x[2]}</small></button>`).join('')}</div></div></div>`}
function quickActions(){const a=[];if(S.age>=6&&S.age<=18)a.push(['school','🎓 Go to school','Attend classes and see what happens']);if(S.age>=6)a.push(['study','📚 Study','Choose a subject in the School panel']);if(S.age>=6)a.push(['friend','👥 See someone','A relationship can change through one afternoon']);a.push(['meal','🍲 Eat','Take care of your body']);a.push(['walk','🚶 Go outside',weatherAdvice()]);if(S.age>=13)a.push(['message','📱 Check messages','People may have contacted you']);return a}

function familyPanel(){return `<div class="dashboard"><div class="card"><h3>Family dynamics</h3><div class="row"><span>Closeness</span><b>${S.family.closeness}%</b></div><div class="row"><span>Tension</span><b>${S.family.tension}%</b></div><button class="action" data-act="familyTalk"><strong>Have a real conversation</strong><small>Build trust, resolve tension or uncover a concern.</small></button></div><div class="card"><h3>Romance & relationships</h3><p><b>${esc(S.romance.status)}</b>${S.romance.partner?' • '+esc(S.romance.partner):''}</p><p class="muted-text">Romance emerges from people, timing and history rather than an automatic match.</p><button class="action" data-act="romance"><strong>Be open to connection</strong><small>See whether an existing relationship changes.</small></button></div></div>`}
function healthPanel(){return `<div class="dashboard"><div class="card"><h3>Health</h3><div class="row"><span>Overall</span><b>${Math.round(S.health)}%</b></div><div class="row"><span>Fitness</span><b>${S.healthState.fitness}%</b></div><div class="row"><span>Sleep quality</span><b>${S.healthState.sleep}%</b></div><div class="row"><span>Current issue</span><b>${esc(S.healthState.illness||'None')}</b></div></div><div class="card"><h3>Care</h3><div class="action-grid"><button class="action" data-act="healthCheck"><strong>🩺 Checkup</strong><small>Spend $15 and address health concerns.</small></button><button class="action" data-act="therapy"><strong>🧠 Mental wellbeing</strong><small>Work on stress and perspective.</small></button><button class="action" data-act="exercise"><strong>🏃 Exercise</strong><small>Build fitness and reduce stress.</small></button></div></div></div>`}
function careerPanel(){return `<div class="dashboard"><div class="card"><h3>Career</h3><div class="row"><span>Current role</span><b>${esc(S.career.job||'None')}</b></div><div class="row"><span>Skills</span><b>${S.career.skills}</b></div><div class="row"><span>Reputation</span><b>${S.career.reputation}</b></div><div class="action-grid"><button class="action" data-act="careerSkill"><strong>Build a skill</strong><small>Practice something useful for future work.</small></button><button class="action" data-act="applyJob"><strong>Look for work</strong><small>Opportunities depend on age and circumstances.</small></button></div></div><div class="card"><h3>Money</h3><div class="row"><span>Cash</span><b>${money(S.money)}</b></div><div class="row"><span>Savings</span><b>${money(S.finance.savings)}</b></div><div class="row"><span>Investments</span><b>${money(S.finance.investments)}</b></div><div class="action-grid"><button class="action" data-act="saveMoney"><strong>Save $25</strong><small>Move cash into savings.</small></button><button class="action" data-act="invest"><strong>Invest up to $50</strong><small>Adult option; returns are uncertain.</small></button></div></div></div>`}
function worldPanel(){return `<div class="dashboard"><div class="card"><h3>Travel</h3><div class="row"><span>Trips taken</span><b>${S.travel.trips}</b></div><p class="muted-text">Trips cost money and time, and can create chance encounters.</p><button class="action" data-act="tripPlan"><strong>Plan a short trip</strong><small>Transport + time + unpredictable encounters.</small></button></div><div class="card"><h3>Online presence</h3><div class="row"><span>Followers</span><b>${S.social.followers}</b></div><div class="row"><span>Posts</span><b>${S.social.posts}</b></div><div class="row"><span>Reputation</span><b>${S.social.reputation}</b></div><button class="action" data-act="social"><strong>Post / interact</strong><small>Attention can grow slowly or suddenly.</small></button></div></div>`}

function renderPanel(){let html=active==='school'?schoolPanel():active==='people'?peoplePanel():active==='phone'?phonePanel():active==='places'?placesPanel():active==='weather'?weatherPanel():active==='business'?businessPanel():active==='family'?familyPanel():active==='health'?healthPanel():active==='career'?careerPanel():active==='world'?worldPanel():homePanel();$('panel-host').innerHTML=html;today()}
function render(){if(!S)return;$('life-name').textContent=S.name;$('life-subtitle').textContent=`Age ${S.age} • Day ${S.day} • ${S.place}`;$('s-age').textContent=S.age;$('s-money').textContent=money(S.money);$('s-health').textContent=Math.round(S.health);$('s-happy').textContent=Math.round(S.happiness);$('s-energy').textContent=Math.round(S.energy);$('s-stress').textContent=Math.round(S.stress);$('s-luck').textContent=Math.round(S.luck)+'%';$('s-mentality').textContent=S.mentality;$('i-place').textContent=S.place;$('i-dob').textContent=S.dob;$('i-zodiac').textContent=S.zodiac;$('i-family').textContent=S.wealth;$('event-meta').textContent=`DAY ${S.day} • AGE ${S.age} • ${S.weather.type.toUpperCase()}`;$('event-title').textContent=S.current.title;$('event-text').textContent=S.current.text;$('event-actions').innerHTML=S.age>=6?`<button data-act="study">Study</button><button data-act="friend">See someone</button><button data-act="message">Check messages</button>`:'';$('people').innerHTML=S.people.slice(0,6).map(p=>`<div class="person"><b>${esc(p.name)}</b><small>${esc(p.mood)} • relationship ${p.rel}</small></div>`).join('');$('tabs').innerHTML=[['home','Overview'],['school','🎓 School'],['people','👥 People'],['phone','📱 Phone'],['places','🏙️ Places'],['weather','🌦️ Weather'],['business','💰 Earn & sell'],['family','❤️ Family & love'],['health','🩺 Health'],['career','💼 Career & money'],['world','🌍 Travel & social']].map(x=>`<button class="tab ${active===x[0]?'active':''}" data-tab="${x[0]}">${x[1]}</button>`).join('');renderPanel();$('log').innerHTML=S.log.map(e=>`<div class="log-entry"><div class="log-date">DAY ${e.day} • AGE ${e.age}</div><b>${esc(e.title)}</b><p>${esc(e.text)}</p></div>`).join('');}
function ageUp(){if(!S)return;const days=365;advance(days);S.age++;S.people=makePeople(S.age);schedule(S.age);ensureEvents();S.energy=100;S.stress=clamp(S.stress-5);setWeather();log('🎂 Birthday',`You turned ${S.age}. A new year begins. People changed, schedules changed, and opportunities are waiting.`);S.current={title:`Age ${S.age}`,text:'A full year passed. Not everything important happened on a button you pressed.'};render();save();toast(`Age ${S.age}!`)}
$('tabs').onclick=e=>{const b=e.target.closest('[data-tab]');if(!b)return;active=b.dataset.tab;render()};
$('panel-host').onclick=e=>{const b=e.target.closest('[data-act],[data-exam],[data-person],[data-person-msg],[data-use],[data-buy],[data-set-stall],[data-set-yardsale],[data-yard-negotiate],[data-event-choice]');if(!b)return;if(b.dataset.exam)act('exam',b.dataset.exam);else if(b.dataset.person!==undefined)act('friend',b.dataset.person);else if(b.dataset.personMsg!==undefined)act('messagePerson',b.dataset.personMsg);else if(b.dataset.use)act('useGear',b.dataset.use);else if(b.dataset.buy){const item=b.dataset.buy,c=gearCost(item);if(S.money<c){toast('Not enough money.');return}S.money-=c;S.inventory[item]++;log('Shopping',`You bought ${gearName(item)} for ${money(c)}.`);render();save();return}else if(b.dataset.setStall){setStallItem();return}else if(b.dataset.setYardsale){S.stall={active:true,type:'Yard Sale',items:[{name:'Used household items',cost:0,price:10,stock:6,quality:60}],revenue:0,visitors:0,day:S.day,exaggeration:20};log('Yard sale','You put selected belongings out for sale. Buyers can bargain and you can decide whether to accept.');render();save();return}else if(b.dataset.yardNegotiate){act('negotiate');return}else if(b.dataset.eventChoice){act('eventChoice',b.dataset.eventChoice);return}else act(b.dataset.act,b.dataset.arg||b.dataset.subject)};
$('event-actions').onclick=e=>{const b=e.target.closest('[data-act]');if(b)act(b.dataset.act)};$('age-up').onclick=ageUp;
$('begin').onclick=()=>{try{S=makeState();enterGame()}catch(err){console.error(err);const box=$('creator-error');box.hidden=false;box.textContent='Could not start life: '+(err?.message||err);}};$('save').onclick=save;$('export').onclick=exportSave;$('load-last').onclick=()=>{const x=localStorage.getItem(KEY);if(!x){toast('No autosave found');return}try{S=JSON.parse(x);migrate();enterGame()}catch{toast('Autosave is invalid')}};$('import-btn').onclick=importFile;$('menu-import').onclick=importFile;$('menu-save').onclick=save;$('menu-export').onclick=exportSave;$('clear-log').onclick=()=>{if(S){S.log=[];render();save()}};$('menu-new').onclick=()=>{S=null;localStorage.removeItem(KEY);$('overlay').classList.add('hidden');$('game').classList.add('hidden');$('creator').classList.remove('hidden')};$('pause').onclick=()=>$('overlay').classList.remove('hidden');$('close-menu').onclick=()=>$('overlay').classList.add('hidden');document.addEventListener('keydown',e=>{if(e.key==='Escape')$('overlay').classList.toggle('hidden')});
function enterGame(){migrate();schedule(S.age);ensureEvents();if(!S.log.length)log('Life begins',S.current.text);$('creator').classList.add('hidden');$('game').classList.remove('hidden');render();save()}
setInterval(()=>{if(S)save()},30000);if(new URLSearchParams(location.search).get('smoke')==='1'){setTimeout(()=>{try{$('begin').click();document.body.dataset.smoke=(!$('game').classList.contains('hidden')&&S)?'pass':'fail'}catch(e){document.body.dataset.smoke='fail';document.body.dataset.smokeError=e.message}},0)}
})();
